package com.views;

import java.awt.*;
import com.basedd.*;
import java.time.LocalDate;
import javax.swing.*;
import java.sql.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;

/* @ChemaPF */
public class MainLog extends javax.swing.JFrame {

    int xMouse, yMouse;
    InicioBD in;
    viewAlumnos vA;
    viewMaterias vM;
    
    LocalDate now = LocalDate.now();
        int year = now.getYear();
        int dia = now.getDayOfMonth();
        int month = now.getMonthValue();
        String[] meses = {"Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto"," ;Septiembre"
            ,"Octubre","Noviembre","Diciemrbre"};
        
    ResultSet rs;
    Statement st;
    
    BDLogin c=new BDLogin();
    Connection conexion;        

    
    public MainLog() {
        initComponents();
        conexion=c.retornoConexion();
        labelFecha.setText("Hoy es "+dia+" de "+meses[month - 1]+" de "+year);
        in=new InicioBD();
        LlenarAlumnos();
        LlenarMaterias();
    }
    
    public final void fecha(){
        //labelFecha.setText(fechacomp);
    }

    public void LlenarAlumnos(){

        try
        {
            DefaultTableModel modelo = new DefaultTableModel();
            tableAlumnos.setModel(modelo);
            tablaCompA.setModel(modelo);

            PreparedStatement ps = null;
            ResultSet rs = null;
            conexion = c.retornoConexion();

            String sql = "Select matricula, nombre, id_u from alumnos;";
            ps = conexion.prepareStatement(sql);
            rs = ps.executeQuery();

            ResultSetMetaData rsMd = rs.getMetaData();

            int cantidadColumnas = rsMd.getColumnCount();

            modelo.addColumn("MATRICULA");
            modelo.addColumn("NOMBRE");
            modelo.addColumn("ID USUARIO");
            
            while(rs.next()){

                Object[] filas = new Object[cantidadColumnas];

                for(int i=0; i< cantidadColumnas; i++){
                    filas[i] = rs.getObject(i + 1);

                }

                modelo.addRow(filas);
            }

        } catch(SQLException ex){
            System.err.println(ex.toString());

        }

    }
    public void LlenarMaterias(){

        try
        {
            DefaultTableModel modelo = new DefaultTableModel();
            tableMaterias.setModel(modelo);
            tablaMatA.setModel(modelo);

            PreparedStatement ps = null;
            ResultSet rs = null;
            conexion = c.retornoConexion();

            String sql = "Select nombrem from materias;";
            ps = conexion.prepareStatement(sql);
            rs = ps.executeQuery();

            ResultSetMetaData rsMd = rs.getMetaData();

            int cantidadColumnas = rsMd.getColumnCount();

            modelo.addColumn("NOMBRE DE LA MATERIA");
            
            
            while(rs.next()){

                Object[] filas = new Object[cantidadColumnas];

                for(int i=0; i< cantidadColumnas; i++){
                    filas[i] = rs.getObject(i + 1);

                }

                modelo.addRow(filas);
            }

        } catch(SQLException ex){
            System.err.println(ex.toString());

        }

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBG = new javax.swing.JPanel();
        BrraTop = new javax.swing.JPanel();
        PnlLogout = new javax.swing.JPanel();
        LogOutimg = new javax.swing.JLabel();
        PnlCerrar = new javax.swing.JPanel();
        BtnCerrar = new javax.swing.JLabel();
        BtnAdmin = new javax.swing.JPanel();
        BtnAdminF = new javax.swing.JLabel();
        TabbedPane2 = new javax.swing.JTabbedPane();
        TabbedPaneOpc1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ImgOnline = new javax.swing.JLabel();
        labelUsr = new javax.swing.JLabel();
        TopperBG = new javax.swing.JPanel();
        panelFecha = new javax.swing.JPanel();
        labelFecha = new javax.swing.JLabel();
        Linea3 = new javax.swing.JPanel();
        Linea2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Linea1 = new javax.swing.JPanel();
        TabbedMenu = new javax.swing.JTabbedPane();
        TabbedOpcDefault = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        PanelIzq = new javax.swing.JPanel();
        BtnComp = new javax.swing.JPanel();
        txtMat = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BtnMat = new javax.swing.JPanel();
        txtCom = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TabbedOpcComp = new javax.swing.JPanel();
        PanelIzq1 = new javax.swing.JPanel();
        BtnComp1 = new javax.swing.JPanel();
        txtMat1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        BtnMat1 = new javax.swing.JPanel();
        txtCom1 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAlumnos = new javax.swing.JTable();
        TabbedOpcMat = new javax.swing.JPanel();
        PanelIzq2 = new javax.swing.JPanel();
        BtnComp2 = new javax.swing.JPanel();
        txtMat2 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        BtnMat2 = new javax.swing.JPanel();
        txtCom2 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableMaterias = new javax.swing.JTable();
        TabbedOpcAdmin = new javax.swing.JPanel();
        PanelIzq3 = new javax.swing.JPanel();
        BtnComp3 = new javax.swing.JPanel();
        txtMat3 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        BtnMat3 = new javax.swing.JPanel();
        txtCom3 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        BtnMA = new javax.swing.JPanel();
        txtMA = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        TabbedA = new javax.swing.JTabbedPane();
        TabbedAM = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        BtnVD = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        TabbedAC = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaCompA = new javax.swing.JTable();
        jLabel37 = new javax.swing.JLabel();
        panelAA = new javax.swing.JPanel();
        btnAAA = new javax.swing.JLabel();
        TabbedAMt = new javax.swing.JPanel();
        panelAM = new javax.swing.JPanel();
        btnAMA = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaMatA = new javax.swing.JTable();
        TabbedOpcIA = new javax.swing.JPanel();
        PanelIzq4 = new javax.swing.JPanel();
        BtnComp4 = new javax.swing.JPanel();
        txtMat4 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        BtnMat4 = new javax.swing.JPanel();
        txtCom4 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        usraTxt = new javax.swing.JTextField();
        passaField = new javax.swing.JPasswordField();
        btnAdminV = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelBG.setBackground(new java.awt.Color(255, 255, 255));
        PanelBG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BrraTop.setBackground(new java.awt.Color(51, 51, 51));
        BrraTop.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BrraTop.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BrraTopMouseDragged(evt);
            }
        });
        BrraTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BrraTopMousePressed(evt);
            }
        });
        BrraTop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PnlLogout.setBackground(new java.awt.Color(51, 51, 51));
        PnlLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PnlLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PnlLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PnlLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PnlLogoutMouseExited(evt);
            }
        });
        PnlLogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogOutimg.setBackground(new java.awt.Color(51, 51, 51));
        LogOutimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/power.png"))); // NOI18N
        LogOutimg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutimgMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogOutimgMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogOutimgMouseExited(evt);
            }
        });
        PnlLogout.add(LogOutimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 2, 40, 40));

        BrraTop.add(PnlLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, 40));

        PnlCerrar.setBackground(new java.awt.Color(51, 51, 51));
        PnlCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PnlCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PnlCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PnlCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PnlCerrarMouseExited(evt);
            }
        });
        PnlCerrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnCerrar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BtnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCerrar.setText("X");
        PnlCerrar.add(BtnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 20, 40));

        BrraTop.add(PnlCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 34, 38));

        BtnAdmin.setBackground(new java.awt.Color(51, 51, 51));
        BtnAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnAdminMouseExited(evt);
            }
        });
        BtnAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnAdminF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/settings-free-icon-font.png"))); // NOI18N
        BtnAdminF.setToolTipText("");
        BtnAdminF.setAlignmentX(0.5F);
        BtnAdminF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAdminFMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnAdminFMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnAdminFMouseExited(evt);
            }
        });
        BtnAdmin.add(BtnAdminF, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 2, 30, 60));

        BrraTop.add(BtnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, -10, 40, 60));

        PanelBG.add(BrraTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 40));

        TabbedPaneOpc1.setBackground(new java.awt.Color(255, 255, 255));
        TabbedPaneOpc1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Conectado");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 125, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/user (2).png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 70, 70));

        ImgOnline.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/accept.png"))); // NOI18N
        jPanel1.add(ImgOnline, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 40, 30));

        labelUsr.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelUsr.setForeground(new java.awt.Color(255, 255, 255));
        labelUsr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUsr.setText("USER");
        jPanel1.add(labelUsr, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 200, -1));

        TabbedPaneOpc1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 250, 180));

        TopperBG.setBackground(new java.awt.Color(51, 51, 51));
        TopperBG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFecha.setBackground(new java.awt.Color(102, 102, 102));
        panelFecha.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelFecha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelFecha.setForeground(new java.awt.Color(255, 255, 255));
        labelFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFecha.setText("FECHA");
        panelFecha.add(labelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 5, 340, -1));

        TopperBG.add(panelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 140, 570, 45));

        Linea3.setBackground(new java.awt.Color(255, 210, 12));

        javax.swing.GroupLayout Linea3Layout = new javax.swing.GroupLayout(Linea3);
        Linea3.setLayout(Linea3Layout);
        Linea3Layout.setHorizontalGroup(
            Linea3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Linea3Layout.setVerticalGroup(
            Linea3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        TopperBG.add(Linea3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 10, 100));

        Linea2.setBackground(new java.awt.Color(255, 210, 12));

        javax.swing.GroupLayout Linea2Layout = new javax.swing.GroupLayout(Linea2);
        Linea2.setLayout(Linea2Layout);
        Linea2Layout.setHorizontalGroup(
            Linea2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Linea2Layout.setVerticalGroup(
            Linea2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        TopperBG.add(Linea2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 350, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MENÚ PRINCIPAL");
        TopperBG.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 35, -1, -1));

        Linea1.setBackground(new java.awt.Color(255, 210, 12));

        javax.swing.GroupLayout Linea1Layout = new javax.swing.GroupLayout(Linea1);
        Linea1.setLayout(Linea1Layout);
        Linea1Layout.setHorizontalGroup(
            Linea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Linea1Layout.setVerticalGroup(
            Linea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        TopperBG.add(Linea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 480, 10));

        TabbedPaneOpc1.add(TopperBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 550, 180));

        TabbedOpcDefault.setBackground(new java.awt.Color(255, 255, 255));
        TabbedOpcDefault.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/code.png"))); // NOI18N
        TabbedOpcDefault.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, 130, 140));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Bienvenido de vuelta!!");
        TabbedOpcDefault.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 200, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Selecciona la opción de tu preferencia.");
        TabbedOpcDefault.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 270, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Recuerda que puedes ver la lista de tus compañeros");
        TabbedOpcDefault.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 340, 70));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("con los que compartes clases");
        TabbedOpcDefault.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 190, 70));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("y a su vez, podras ver una lista de");
        TabbedOpcDefault.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 220, 70));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("materias las cuales esten dentro de la Base de Datos.");
        TabbedOpcDefault.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 360, 70));

        PanelIzq.setBackground(new java.awt.Color(204, 204, 204));
        PanelIzq.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnComp.setBackground(new java.awt.Color(51, 51, 51));
        BtnComp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnComp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCompMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnCompMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnCompMouseExited(evt);
            }
        });
        BtnComp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMat.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtMat.setForeground(new java.awt.Color(255, 255, 255));
        txtMat.setText("Materias");
        BtnComp.add(txtMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 25, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/book.png"))); // NOI18N
        BtnComp.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 25, 40, 30));

        PanelIzq.add(BtnComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 250, 80));

        BtnMat.setBackground(new java.awt.Color(51, 51, 51));
        BtnMat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnMat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnMatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnMatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnMatMouseExited(evt);
            }
        });
        BtnMat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCom.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtCom.setForeground(new java.awt.Color(255, 255, 255));
        txtCom.setText("Compañeros");
        BtnMat.add(txtCom, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 25, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/graduation-hat_1.png"))); // NOI18N
        BtnMat.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 27, 40, 30));

        PanelIzq.add(BtnMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 250, 80));

        TabbedOpcDefault.add(PanelIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 240, 360));

        TabbedMenu.addTab("tab2", TabbedOpcDefault);

        TabbedOpcComp.setBackground(new java.awt.Color(255, 255, 255));
        TabbedOpcComp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelIzq1.setBackground(new java.awt.Color(204, 204, 204));
        PanelIzq1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnComp1.setBackground(new java.awt.Color(51, 51, 51));
        BtnComp1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnComp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnComp1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnComp1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnComp1MouseExited(evt);
            }
        });
        BtnComp1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMat1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtMat1.setForeground(new java.awt.Color(255, 255, 255));
        txtMat1.setText("Materias");
        BtnComp1.add(txtMat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 25, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/book.png"))); // NOI18N
        BtnComp1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 25, 40, 30));

        PanelIzq1.add(BtnComp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 250, 80));

        BtnMat1.setBackground(new java.awt.Color(51, 51, 51));
        BtnMat1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnMat1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnMat1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnMat1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnMat1MouseExited(evt);
            }
        });
        BtnMat1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCom1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtCom1.setForeground(new java.awt.Color(255, 255, 255));
        txtCom1.setText("Compañeros");
        BtnMat1.add(txtCom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 25, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/graduation-hat_1.png"))); // NOI18N
        BtnMat1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 27, 40, 30));

        PanelIzq1.add(BtnMat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 250, 80));

        TabbedOpcComp.add(PanelIzq1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 240, 360));

        jLabel34.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel34.setText("COMPAÑEROS");
        TabbedOpcComp.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, -1));

        tableAlumnos.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tableAlumnos);

        TabbedOpcComp.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, 160));

        TabbedMenu.addTab("tab1", TabbedOpcComp);

        TabbedOpcMat.setBackground(new java.awt.Color(255, 255, 255));
        TabbedOpcMat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelIzq2.setBackground(new java.awt.Color(204, 204, 204));
        PanelIzq2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnComp2.setBackground(new java.awt.Color(51, 51, 51));
        BtnComp2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnComp2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnComp2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnComp2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnComp2MouseExited(evt);
            }
        });
        BtnComp2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMat2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtMat2.setForeground(new java.awt.Color(255, 255, 255));
        txtMat2.setText("Materias");
        BtnComp2.add(txtMat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 25, -1, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/book.png"))); // NOI18N
        BtnComp2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 25, 40, 30));

        PanelIzq2.add(BtnComp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 250, 80));

        BtnMat2.setBackground(new java.awt.Color(51, 51, 51));
        BtnMat2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnMat2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnMat2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnMat2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnMat2MouseExited(evt);
            }
        });
        BtnMat2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCom2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtCom2.setForeground(new java.awt.Color(255, 255, 255));
        txtCom2.setText("Compañeros");
        BtnMat2.add(txtCom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 25, -1, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/graduation-hat_1.png"))); // NOI18N
        BtnMat2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 27, 40, 30));

        PanelIzq2.add(BtnMat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 250, 80));

        TabbedOpcMat.add(PanelIzq2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 240, 360));

        jLabel35.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel35.setText("MATERIAS");
        TabbedOpcMat.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        tableMaterias.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(tableMaterias);

        TabbedOpcMat.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 330, 160));

        TabbedMenu.addTab("tab3", TabbedOpcMat);

        TabbedOpcAdmin.setBackground(new java.awt.Color(255, 255, 255));
        TabbedOpcAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelIzq3.setBackground(new java.awt.Color(204, 204, 204));
        PanelIzq3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnComp3.setBackground(new java.awt.Color(51, 51, 51));
        BtnComp3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnComp3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnComp3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnComp3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnComp3MouseExited(evt);
            }
        });
        BtnComp3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMat3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtMat3.setForeground(new java.awt.Color(255, 255, 255));
        txtMat3.setText("Materias");
        BtnComp3.add(txtMat3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/book.png"))); // NOI18N
        BtnComp3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 40, 30));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("ADMIN");
        BtnComp3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 55, -1, -1));

        PanelIzq3.add(BtnComp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 250, 80));

        BtnMat3.setBackground(new java.awt.Color(51, 51, 51));
        BtnMat3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnMat3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnMat3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnMat3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnMat3MouseExited(evt);
            }
        });
        BtnMat3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCom3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtCom3.setForeground(new java.awt.Color(255, 255, 255));
        txtCom3.setText("Compañeros");
        BtnMat3.add(txtCom3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/graduation-hat_1.png"))); // NOI18N
        BtnMat3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 40, 30));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("ADMIN");
        BtnMat3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 55, -1, -1));

        PanelIzq3.add(BtnMat3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 250, 80));

        BtnMA.setBackground(new java.awt.Color(51, 51, 51));
        BtnMA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnMA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnMAMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnMAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnMAMouseExited(evt);
            }
        });
        BtnMA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMA.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtMA.setForeground(new java.awt.Color(255, 255, 255));
        txtMA.setText("   MENU");
        BtnMA.add(txtMA, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/apps-free-icon-font.png"))); // NOI18N
        BtnMA.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 40, 30));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("ADMIN");
        BtnMA.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        PanelIzq3.add(BtnMA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 250, 80));

        TabbedOpcAdmin.add(PanelIzq3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 240, 360));

        TabbedAM.setBackground(new java.awt.Color(255, 255, 255));
        TabbedAM.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("BIENVENIDO A LA VISTA ADMIN");
        TabbedAM.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("alumnos registrados en la BDD.");
        TabbedAM.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 310, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Selecciona la opción de tu preferencia.");
        TabbedAM.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 250, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Desde aca podrás consultar, actualizar o eliminar");
        TabbedAM.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 310, 30));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/management (1).png"))); // NOI18N
        TabbedAM.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, 140));

        BtnVD.setBackground(new java.awt.Color(51, 51, 51));
        BtnVD.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel19.setBackground(new java.awt.Color(255, 153, 51));
        jLabel19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("    Regresar a la vista normal");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel19MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel19MouseExited(evt);
            }
        });

        javax.swing.GroupLayout BtnVDLayout = new javax.swing.GroupLayout(BtnVD);
        BtnVD.setLayout(BtnVDLayout);
        BtnVDLayout.setHorizontalGroup(
            BtnVDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
            .addGroup(BtnVDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
        );
        BtnVDLayout.setVerticalGroup(
            BtnVDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(BtnVDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
        );

        TabbedAM.add(BtnVD, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 220, 40));

        TabbedA.addTab("tab1", TabbedAM);

        TabbedAC.setBackground(new java.awt.Color(255, 255, 255));
        TabbedAC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(51, 51, 51));
        jLabel36.setText("VISTA DE COMPAÑEROS ADMIN");
        TabbedAC.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, 30));

        jScrollPane4.setViewportView(tablaCompA);

        TabbedAC.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, 120));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(51, 51, 51));
        jLabel37.setText("Alumnos:");
        TabbedAC.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));

        panelAA.setBackground(new java.awt.Color(51, 51, 51));
        panelAA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelAA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAAA.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAAA.setForeground(new java.awt.Color(255, 255, 255));
        btnAAA.setText("          ENTRAR");
        btnAAA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAAA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAAAMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAAAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAAAMouseExited(evt);
            }
        });
        panelAA.add(btnAAA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 40));

        TabbedAC.add(panelAA, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 130, 40));

        TabbedA.addTab("tab2", TabbedAC);

        TabbedAMt.setBackground(new java.awt.Color(255, 255, 255));
        TabbedAMt.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelAM.setBackground(new java.awt.Color(51, 51, 51));
        panelAM.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelAM.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAMA.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAMA.setForeground(new java.awt.Color(255, 255, 255));
        btnAMA.setText("          ENTRAR");
        btnAMA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAMA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAMAMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAMAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAMAMouseExited(evt);
            }
        });
        panelAM.add(btnAMA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 40));

        TabbedAMt.add(panelAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 130, 40));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(51, 51, 51));
        jLabel40.setText("Materias:");
        TabbedAMt.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(51, 51, 51));
        jLabel41.setText("VISTA DE MATERIAS ADMIN");
        TabbedAMt.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, 30));

        jScrollPane5.setViewportView(tablaMatA);

        TabbedAMt.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 290, 120));

        TabbedA.addTab("tab3", TabbedAMt);

        TabbedOpcAdmin.add(TabbedA, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 570, 400));

        TabbedMenu.addTab("tab4", TabbedOpcAdmin);

        TabbedOpcIA.setBackground(new java.awt.Color(255, 255, 255));
        TabbedOpcIA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelIzq4.setBackground(new java.awt.Color(204, 204, 204));
        PanelIzq4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnComp4.setBackground(new java.awt.Color(51, 51, 51));
        BtnComp4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnComp4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnComp4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnComp4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnComp4MouseExited(evt);
            }
        });
        BtnComp4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMat4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtMat4.setForeground(new java.awt.Color(255, 255, 255));
        txtMat4.setText("Materias");
        BtnComp4.add(txtMat4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 25, -1, -1));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/book.png"))); // NOI18N
        BtnComp4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 25, 40, 30));

        PanelIzq4.add(BtnComp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 250, 80));

        BtnMat4.setBackground(new java.awt.Color(51, 51, 51));
        BtnMat4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnMat4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnMat4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnMat4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnMat4MouseExited(evt);
            }
        });
        BtnMat4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCom4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtCom4.setForeground(new java.awt.Color(255, 255, 255));
        txtCom4.setText("Compañeros");
        BtnMat4.add(txtCom4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 25, -1, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/graduation-hat_1.png"))); // NOI18N
        BtnMat4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 27, 40, 30));

        PanelIzq4.add(BtnMat4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 250, 80));

        TabbedOpcIA.add(PanelIzq4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 240, 360));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 51, 51));
        jLabel30.setText("Contraseña:");
        TabbedOpcIA.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 110, 30));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 51, 51));
        jLabel31.setText("INICIA SESIÓN CON PERFIL DE ADMIN");
        TabbedOpcIA.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, 30));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(51, 51, 51));
        jLabel32.setText("Usuario:");
        TabbedOpcIA.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, 30));
        TabbedOpcIA.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 270, 10));
        TabbedOpcIA.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 270, 10));

        usraTxt.setBackground(new java.awt.Color(255, 255, 255));
        usraTxt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        usraTxt.setForeground(java.awt.Color.lightGray);
        usraTxt.setText("Ingrese el nombre de usuario.");
        usraTxt.setBorder(null);
        usraTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usraTxtMousePressed(evt);
            }
        });
        usraTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usraTxtActionPerformed(evt);
            }
        });
        TabbedOpcIA.add(usraTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 270, 30));

        passaField.setBackground(new java.awt.Color(255, 255, 255));
        passaField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        passaField.setForeground(java.awt.Color.lightGray);
        passaField.setText("********");
        passaField.setBorder(null);
        passaField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passaFieldMousePressed(evt);
            }
        });
        TabbedOpcIA.add(passaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 260, 30));

        btnAdminV.setBackground(new java.awt.Color(51, 51, 51));
        btnAdminV.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAdminV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdminVMouseClicked(evt);
            }
        });
        btnAdminV.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("         INICIAR");
        jLabel33.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel33MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel33MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel33MouseExited(evt);
            }
        });
        btnAdminV.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, -4, 150, 70));

        TabbedOpcIA.add(btnAdminV, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 150, 60));

        TabbedMenu.addTab("tab5", TabbedOpcIA);

        TabbedPaneOpc1.add(TabbedMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 800, 440));

        TabbedPane2.addTab("tab1", TabbedPaneOpc1);

        PanelBG.add(TabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 800, 580));

        getContentPane().add(PanelBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PnlCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_PnlCerrarMouseClicked

    private void PnlCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlCerrarMouseEntered
        PnlCerrar.setBackground(Color.red);
        BtnCerrar.setForeground(Color.white);
    }//GEN-LAST:event_PnlCerrarMouseEntered

    private void PnlCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlCerrarMouseExited
        PnlCerrar.setBackground(new Color(51, 51, 51));
        BtnCerrar.setForeground(Color.white);
    }//GEN-LAST:event_PnlCerrarMouseExited

    private void BrraTopMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BrraTopMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_BrraTopMouseDragged

    private void BrraTopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BrraTopMousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_BrraTopMousePressed

    private void BtnMatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMatMouseEntered
        BtnMat.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_BtnMatMouseEntered

    private void BtnMatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMatMouseExited
        BtnMat.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_BtnMatMouseExited

    private void BtnCompMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCompMouseEntered
        
        BtnComp.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_BtnCompMouseEntered

    private void BtnCompMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCompMouseExited
        BtnComp.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_BtnCompMouseExited

    private void PnlLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlLogoutMouseClicked
        this.dispose();
        MenuLog ini = new MenuLog();
        ini.setVisible(true);
        ini.setResizable(false);
        ini.setLocationRelativeTo(null);
    }//GEN-LAST:event_PnlLogoutMouseClicked

    private void PnlLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlLogoutMouseEntered
        PnlLogout.setBackground(new Color(255, 210, 12));
    }//GEN-LAST:event_PnlLogoutMouseEntered

    private void PnlLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlLogoutMouseExited
        PnlLogout.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_PnlLogoutMouseExited

    private void LogOutimgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutimgMouseEntered
        PnlLogout.setBackground(new Color(255, 210, 12));
    }//GEN-LAST:event_LogOutimgMouseEntered

    private void LogOutimgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutimgMouseExited
        PnlLogout.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_LogOutimgMouseExited

    private void LogOutimgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutimgMouseClicked
        this.dispose();
        MenuLog ini = new MenuLog();
        ini.setVisible(true);
        ini.setResizable(false);
        ini.setLocationRelativeTo(null);
    }//GEN-LAST:event_LogOutimgMouseClicked

    private void BtnMatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMatMouseClicked
        BtnMat1.setBackground(new Color(153, 153, 153));
        TabbedMenu.setSelectedIndex(1);
    }//GEN-LAST:event_BtnMatMouseClicked

    private void BtnCompMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCompMouseClicked
        TabbedMenu.setSelectedIndex(2);
        BtnComp2.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_BtnCompMouseClicked

    private void jLabel19MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseEntered
        BtnVD.setBackground(new Color(249, 157, 19));
        jLabel19.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel19MouseEntered

    private void jLabel19MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseExited
        BtnVD.setBackground(new Color(51, 51, 51));
        jLabel19.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel19MouseExited

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        TabbedMenu.setSelectedIndex(0);
    }//GEN-LAST:event_jLabel19MouseClicked

    private void BtnComp1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnComp1MouseClicked
        TabbedMenu.setSelectedIndex(2);
    }//GEN-LAST:event_BtnComp1MouseClicked

    private void BtnComp1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnComp1MouseEntered
        BtnComp1.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_BtnComp1MouseEntered

    private void BtnComp1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnComp1MouseExited
        BtnComp1.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_BtnComp1MouseExited

    private void BtnMat1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMat1MouseClicked
        TabbedMenu.setSelectedIndex(1);
    }//GEN-LAST:event_BtnMat1MouseClicked

    private void BtnMat1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMat1MouseEntered
        BtnMat1.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_BtnMat1MouseEntered

    private void BtnMat1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMat1MouseExited
        BtnMat1.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_BtnMat1MouseExited

    private void BtnComp2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnComp2MouseClicked
        TabbedMenu.setSelectedIndex(2);
    }//GEN-LAST:event_BtnComp2MouseClicked

    private void BtnComp2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnComp2MouseEntered
        BtnComp2.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_BtnComp2MouseEntered

    private void BtnComp2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnComp2MouseExited
        BtnComp2.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_BtnComp2MouseExited

    private void BtnMat2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMat2MouseClicked
        TabbedMenu.setSelectedIndex(1);
    }//GEN-LAST:event_BtnMat2MouseClicked

    private void BtnMat2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMat2MouseEntered
        BtnMat2.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_BtnMat2MouseEntered

    private void BtnMat2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMat2MouseExited
        BtnMat2.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_BtnMat2MouseExited

    private void BtnComp3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnComp3MouseClicked
        TabbedA.setSelectedIndex(2);
    }//GEN-LAST:event_BtnComp3MouseClicked

    private void BtnComp3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnComp3MouseEntered
        BtnComp3.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_BtnComp3MouseEntered

    private void BtnComp3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnComp3MouseExited
        BtnComp3.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_BtnComp3MouseExited

    private void BtnMat3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMat3MouseClicked
        TabbedA.setSelectedIndex(1);
    }//GEN-LAST:event_BtnMat3MouseClicked

    private void BtnMat3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMat3MouseEntered
        BtnMat3.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_BtnMat3MouseEntered

    private void BtnMat3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMat3MouseExited
        BtnMat3.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_BtnMat3MouseExited

    private void BtnAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAdminMouseEntered
        BtnAdmin.setBackground(Color.white);
    }//GEN-LAST:event_BtnAdminMouseEntered

    private void BtnAdminFMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAdminFMouseEntered
        BtnAdmin.setBackground(Color.white);
    }//GEN-LAST:event_BtnAdminFMouseEntered

    private void BtnAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAdminMouseExited
        BtnAdmin.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_BtnAdminMouseExited

    private void BtnAdminFMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAdminFMouseExited
        BtnAdmin.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_BtnAdminFMouseExited

    private void BtnAdminFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAdminFMouseClicked
        TabbedMenu.setSelectedIndex(4);
        
    }//GEN-LAST:event_BtnAdminFMouseClicked

    private void BtnAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAdminMouseClicked
        TabbedMenu.setSelectedIndex(4);
    }//GEN-LAST:event_BtnAdminMouseClicked

    private void BtnComp4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnComp4MouseClicked
        TabbedMenu.setSelectedIndex(2);
    }//GEN-LAST:event_BtnComp4MouseClicked

    private void BtnComp4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnComp4MouseEntered
        BtnComp4.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_BtnComp4MouseEntered

    private void BtnComp4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnComp4MouseExited
        BtnComp4.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_BtnComp4MouseExited

    private void BtnMat4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMat4MouseClicked
        TabbedMenu.setSelectedIndex(1);
    }//GEN-LAST:event_BtnMat4MouseClicked

    private void BtnMat4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMat4MouseEntered
        BtnMat4.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_BtnMat4MouseEntered

    private void BtnMat4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMat4MouseExited
        BtnMat4.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_BtnMat4MouseExited

    private void usraTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usraTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usraTxtActionPerformed

    private void jLabel33MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseEntered
        btnAdminV.setBackground(new Color(152, 153, 153));
        jLabel33.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_jLabel33MouseEntered

    private void jLabel33MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseExited
        btnAdminV.setBackground(new Color(51, 51, 51));
        jLabel33.setForeground(Color.white);
    }//GEN-LAST:event_jLabel33MouseExited

    private void usraTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usraTxtMousePressed
        if (usraTxt.getText().equals("Ingrese el nombre de usuario.")){
        usraTxt.setText("");
        usraTxt.setForeground(Color.black);
    }
        if (String.valueOf(passaField.getPassword()).isEmpty()){
            passaField.setText("********");
            passaField.setForeground(Color.lightGray);
        } 
    }//GEN-LAST:event_usraTxtMousePressed

    private void passaFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passaFieldMousePressed
        if (String.valueOf(passaField.getPassword()).equals("********")){
        passaField.setText("");
        passaField.setForeground(Color.black);
    }
        if (usraTxt.getText().isEmpty()){
            usraTxt.setText("Ingrese el nombre de usuario.");
            usraTxt.setForeground(Color.lightGray);
        }
    }//GEN-LAST:event_passaFieldMousePressed

    private void jLabel33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseClicked
        
        String usuario="ADMIN";
        String pass="ADMIN";
        
        if(usuario.equals(usraTxt.getText())){
            if(pass.equals(String.valueOf(passaField.getPassword()))){
                TabbedMenu.setSelectedIndex(3);
            }else{
                usraTxt.setText("Ingrese el nombre de usuario.");
                usraTxt.setForeground(Color.lightGray);
                passaField.setText("********");
                passaField.setForeground(Color.lightGray);
                JOptionPane.showMessageDialog(null, "Usuario y/o contraseña incorrectos.");
            }
        }else{
                usraTxt.setText("Ingrese el nombre de usuario.");
                usraTxt.setForeground(Color.lightGray);
                passaField.setText("********");
                passaField.setForeground(Color.lightGray);
                JOptionPane.showMessageDialog(null, "Usuario y/o contraseña incorrectos.");
        }
    }//GEN-LAST:event_jLabel33MouseClicked

    private void btnAdminVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminVMouseClicked
        String usuario="ADMIN";
        String pass="ADMIN";
        
        if(usuario.equals(usraTxt.getText())){
            if(pass.equals(String.valueOf(passaField.getPassword()))){
                TabbedMenu.setSelectedIndex(3);
            }else{
                usraTxt.setText("Ingrese el nombre de usuario.");
                usraTxt.setForeground(Color.lightGray);
                passaField.setText("********");
                passaField.setForeground(Color.lightGray);
                JOptionPane.showMessageDialog(null, "Usuario y/o contraseña incorrectos.");
            }
        }
    }//GEN-LAST:event_btnAdminVMouseClicked

    private void btnAAAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAAAMouseEntered
        panelAA.setBackground(new Color(153, 153, 153));
        btnAAA.setForeground(Color.darkGray);
    }//GEN-LAST:event_btnAAAMouseEntered

    private void btnAAAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAAAMouseExited
        panelAA.setBackground(new Color(51, 51, 51));
        btnAAA.setForeground(Color.white);
    }//GEN-LAST:event_btnAAAMouseExited

    private void btnAMAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAMAMouseEntered
        panelAM.setBackground(new Color(153, 153, 153));
        btnAMA.setForeground(Color.darkGray);
    }//GEN-LAST:event_btnAMAMouseEntered

    private void btnAMAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAMAMouseExited
        panelAM.setBackground(new Color(51, 51, 51));
        btnAMA.setForeground(Color.white);
    }//GEN-LAST:event_btnAMAMouseExited

    private void BtnMAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMAMouseClicked
        TabbedA.setSelectedIndex(0);
    }//GEN-LAST:event_BtnMAMouseClicked

    private void BtnMAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMAMouseEntered
        BtnMA.setBackground(Color.lightGray);
        txtMA.setForeground(Color.darkGray);
    }//GEN-LAST:event_BtnMAMouseEntered

    private void BtnMAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMAMouseExited
        BtnMA.setBackground(new Color(51, 51, 51));
        txtMA.setForeground(Color.white);
    }//GEN-LAST:event_BtnMAMouseExited

    private void btnAAAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAAAMouseClicked
        vA=new viewAlumnos();
        this.dispose();
        vA.setVisible(true);
        vA.setResizable(false);
        vA.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_btnAAAMouseClicked

    private void btnAMAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAMAMouseClicked
        vM=new viewMaterias();
        this.dispose();
        vM.setVisible(true);
        vM.setResizable(false);
        vM.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_btnAMAMouseClicked


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainLog().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BrraTop;
    private javax.swing.JPanel BtnAdmin;
    private javax.swing.JLabel BtnAdminF;
    private javax.swing.JLabel BtnCerrar;
    private javax.swing.JPanel BtnComp;
    private javax.swing.JPanel BtnComp1;
    private javax.swing.JPanel BtnComp2;
    private javax.swing.JPanel BtnComp3;
    private javax.swing.JPanel BtnComp4;
    private javax.swing.JPanel BtnMA;
    private javax.swing.JPanel BtnMat;
    private javax.swing.JPanel BtnMat1;
    private javax.swing.JPanel BtnMat2;
    private javax.swing.JPanel BtnMat3;
    private javax.swing.JPanel BtnMat4;
    private javax.swing.JPanel BtnVD;
    private javax.swing.JLabel ImgOnline;
    private javax.swing.JPanel Linea1;
    private javax.swing.JPanel Linea2;
    private javax.swing.JPanel Linea3;
    private javax.swing.JLabel LogOutimg;
    private javax.swing.JPanel PanelBG;
    private javax.swing.JPanel PanelIzq;
    private javax.swing.JPanel PanelIzq1;
    private javax.swing.JPanel PanelIzq2;
    private javax.swing.JPanel PanelIzq3;
    private javax.swing.JPanel PanelIzq4;
    private javax.swing.JPanel PnlCerrar;
    private javax.swing.JPanel PnlLogout;
    private javax.swing.JTabbedPane TabbedA;
    private javax.swing.JPanel TabbedAC;
    private javax.swing.JPanel TabbedAM;
    private javax.swing.JPanel TabbedAMt;
    private javax.swing.JTabbedPane TabbedMenu;
    private javax.swing.JPanel TabbedOpcAdmin;
    private javax.swing.JPanel TabbedOpcComp;
    private javax.swing.JPanel TabbedOpcDefault;
    private javax.swing.JPanel TabbedOpcIA;
    private javax.swing.JPanel TabbedOpcMat;
    private javax.swing.JTabbedPane TabbedPane2;
    private javax.swing.JPanel TabbedPaneOpc1;
    private javax.swing.JPanel TopperBG;
    private javax.swing.JLabel btnAAA;
    private javax.swing.JLabel btnAMA;
    private javax.swing.JPanel btnAdminV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelFecha;
    public static javax.swing.JLabel labelUsr;
    private javax.swing.JPanel panelAA;
    private javax.swing.JPanel panelAM;
    private javax.swing.JPanel panelFecha;
    private javax.swing.JPasswordField passaField;
    private javax.swing.JTable tablaCompA;
    private javax.swing.JTable tablaMatA;
    private javax.swing.JTable tableAlumnos;
    private javax.swing.JTable tableMaterias;
    private javax.swing.JLabel txtCom;
    private javax.swing.JLabel txtCom1;
    private javax.swing.JLabel txtCom2;
    private javax.swing.JLabel txtCom3;
    private javax.swing.JLabel txtCom4;
    private javax.swing.JLabel txtMA;
    private javax.swing.JLabel txtMat;
    private javax.swing.JLabel txtMat1;
    private javax.swing.JLabel txtMat2;
    private javax.swing.JLabel txtMat3;
    private javax.swing.JLabel txtMat4;
    private javax.swing.JTextField usraTxt;
    // End of variables declaration//GEN-END:variables
}
