package com.views;
import com.basedd.*;
import java.awt.*;
import java.sql.*;
import javax.swing.*;

/* @ChemaPF */
public class MenuLog extends javax.swing.JFrame {

    int xMouse, yMouse; 
    InicioBD in;
    RegistroBD reg;
    ActualizarBD upd;
    MainLog menu;
    
    public MenuLog() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        upd=new ActualizarBD();
        in=new InicioBD();
        reg=new RegistroBD();
        menu=new MainLog();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        imgLog = new javax.swing.JLabel();
        BrraTop = new javax.swing.JPanel();
        PnlCerrar = new javax.swing.JPanel();
        BtnCerrar = new javax.swing.JLabel();
        TabbedPane = new javax.swing.JTabbedPane();
        Inicio = new javax.swing.JPanel();
        LabelLog = new javax.swing.JLabel();
        ImgLog = new javax.swing.JLabel();
        LabelUser = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        LabelPass = new javax.swing.JLabel();
        userTxt = new javax.swing.JTextField();
        passField = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        BtnLog = new javax.swing.JPanel();
        LableLogBtn = new javax.swing.JLabel();
        Sign = new javax.swing.JLabel();
        OlvPass = new javax.swing.JLabel();
        Registro = new javax.swing.JPanel();
        ImgSign = new javax.swing.JLabel();
        LabelSign = new javax.swing.JLabel();
        LabelUser1 = new javax.swing.JLabel();
        userTxtR = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        LabelPass1 = new javax.swing.JLabel();
        passFieldR = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        BtnLog1 = new javax.swing.JPanel();
        LableLogBtn1 = new javax.swing.JLabel();
        ImgBack = new javax.swing.JLabel();
        Actualizar = new javax.swing.JPanel();
        ImgAct = new javax.swing.JLabel();
        LabelSign1 = new javax.swing.JLabel();
        LabelUser2 = new javax.swing.JLabel();
        usrTxtUpd = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        BtnLog2 = new javax.swing.JPanel();
        LableLogBtn2 = new javax.swing.JLabel();
        ImgBack1 = new javax.swing.JLabel();
        Actualizar2 = new javax.swing.JPanel();
        ImgAct2 = new javax.swing.JLabel();
        LabelSign2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        LabelPass2 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        BtnUpd2 = new javax.swing.JPanel();
        LableUpdBtn = new javax.swing.JLabel();
        ImgBack2 = new javax.swing.JLabel();
        nvPass2 = new javax.swing.JPasswordField();
        nvPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        BG.setBackground(new java.awt.Color(255, 255, 255));
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgLog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/pexels-element-digital-1370296 (1).jpg"))); // NOI18N
        BG.add(imgLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, -40, 300, 650));

        BrraTop.setBackground(new java.awt.Color(255, 255, 255));
        BrraTop.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BrraTopMouseDragged(evt);
            }
        });
        BrraTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BrraTopMousePressed(evt);
            }
        });

        PnlCerrar.setBackground(new java.awt.Color(255, 255, 255));
        PnlCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PnlCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PnlCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PnlCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PnlCerrarMouseExited(evt);
            }
        });
        PnlCerrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnCerrar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BtnCerrar.setForeground(new java.awt.Color(0, 0, 0));
        BtnCerrar.setText("X");
        PnlCerrar.add(BtnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 32, 40));

        javax.swing.GroupLayout BrraTopLayout = new javax.swing.GroupLayout(BrraTop);
        BrraTop.setLayout(BrraTopLayout);
        BrraTopLayout.setHorizontalGroup(
            BrraTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BrraTopLayout.createSequentialGroup()
                .addComponent(PnlCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 756, Short.MAX_VALUE))
        );
        BrraTopLayout.setVerticalGroup(
            BrraTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BrraTopLayout.createSequentialGroup()
                .addComponent(PnlCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        BG.add(BrraTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 40));

        Inicio.setBackground(new java.awt.Color(255, 255, 255));
        Inicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelLog.setFont(new java.awt.Font("Dialog", 1, 33)); // NOI18N
        LabelLog.setForeground(new java.awt.Color(51, 51, 51));
        LabelLog.setText("INICIAR SESIÓN");
        Inicio.add(LabelLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 290, 40));

        ImgLog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/login (1).png"))); // NOI18N
        Inicio.add(ImgLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 70, 60));

        LabelUser.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        LabelUser.setForeground(new java.awt.Color(51, 51, 51));
        LabelUser.setText("Usuario");
        Inicio.add(LabelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));
        Inicio.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 340, 20));

        LabelPass.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        LabelPass.setForeground(new java.awt.Color(51, 51, 51));
        LabelPass.setText("Contraseña");
        Inicio.add(LabelPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        userTxt.setBackground(new java.awt.Color(255, 255, 255));
        userTxt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        userTxt.setForeground(new java.awt.Color(204, 204, 204));
        userTxt.setText("Ingrese su nombre de usuario.");
        userTxt.setBorder(null);
        userTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userTxtMousePressed(evt);
            }
        });
        Inicio.add(userTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 340, 30));

        passField.setBackground(new java.awt.Color(255, 255, 255));
        passField.setForeground(new java.awt.Color(204, 204, 204));
        passField.setText("********");
        passField.setBorder(null);
        passField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passFieldMousePressed(evt);
            }
        });
        passField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passFieldActionPerformed(evt);
            }
        });
        Inicio.add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 340, 30));
        Inicio.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 340, 20));

        BtnLog.setBackground(new java.awt.Color(255, 210, 12));
        BtnLog.setForeground(new java.awt.Color(255, 210, 8));
        BtnLog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnLog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnLogMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnLogMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnLogMouseExited(evt);
            }
        });

        LableLogBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        LableLogBtn.setForeground(new java.awt.Color(0, 0, 0));
        LableLogBtn.setText("     ENTRAR");
        LableLogBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LableLogBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LableLogBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LableLogBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LableLogBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LableLogBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BtnLogLayout = new javax.swing.GroupLayout(BtnLog);
        BtnLog.setLayout(BtnLogLayout);
        BtnLogLayout.setHorizontalGroup(
            BtnLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LableLogBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        BtnLogLayout.setVerticalGroup(
            BtnLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LableLogBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        Inicio.add(BtnLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 120, 50));

        Sign.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Sign.setForeground(new java.awt.Color(0, 0, 0));
        Sign.setText("Registrarse");
        Sign.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignMouseExited(evt);
            }
        });
        Inicio.add(Sign, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, -1, -1));

        OlvPass.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        OlvPass.setForeground(new java.awt.Color(0, 0, 0));
        OlvPass.setText("¿Olvidaste tu contraseña?");
        OlvPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OlvPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OlvPassMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OlvPassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OlvPassMouseExited(evt);
            }
        });
        Inicio.add(OlvPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, -1, -1));

        TabbedPane.addTab("tab1", Inicio);

        Registro.setBackground(new java.awt.Color(255, 255, 255));
        Registro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Registro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImgSign.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/user.png"))); // NOI18N
        Registro.add(ImgSign, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 70, 90));

        LabelSign.setFont(new java.awt.Font("Dialog", 1, 33)); // NOI18N
        LabelSign.setForeground(new java.awt.Color(51, 51, 51));
        LabelSign.setText("CREAR UNA SESIÓN");
        Registro.add(LabelSign, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 360, 40));

        LabelUser1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        LabelUser1.setForeground(new java.awt.Color(51, 51, 51));
        LabelUser1.setText("Usuario");
        Registro.add(LabelUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        userTxtR.setBackground(new java.awt.Color(255, 255, 255));
        userTxtR.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        userTxtR.setForeground(new java.awt.Color(204, 204, 204));
        userTxtR.setText("Ingrese su nombre de usuario.");
        userTxtR.setBorder(null);
        userTxtR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userTxtRMousePressed(evt);
            }
        });
        userTxtR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTxtRActionPerformed(evt);
            }
        });
        Registro.add(userTxtR, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 340, 30));
        Registro.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 340, 20));

        LabelPass1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        LabelPass1.setForeground(new java.awt.Color(51, 51, 51));
        LabelPass1.setText("Contraseña");
        Registro.add(LabelPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        passFieldR.setBackground(new java.awt.Color(255, 255, 255));
        passFieldR.setForeground(new java.awt.Color(204, 204, 204));
        passFieldR.setText("********");
        passFieldR.setBorder(null);
        passFieldR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passFieldRMousePressed(evt);
            }
        });
        passFieldR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passFieldRActionPerformed(evt);
            }
        });
        Registro.add(passFieldR, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 340, 30));
        Registro.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 340, 20));

        BtnLog1.setBackground(new java.awt.Color(255, 210, 12));
        BtnLog1.setForeground(new java.awt.Color(255, 210, 8));
        BtnLog1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnLog1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnLog1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnLog1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnLog1MouseExited(evt);
            }
        });

        LableLogBtn1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        LableLogBtn1.setForeground(new java.awt.Color(0, 0, 0));
        LableLogBtn1.setText("REGISTRAR");
        LableLogBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout BtnLog1Layout = new javax.swing.GroupLayout(BtnLog1);
        BtnLog1.setLayout(BtnLog1Layout);
        BtnLog1Layout.setHorizontalGroup(
            BtnLog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BtnLog1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(LableLogBtn1)
                .addGap(21, 21, 21))
        );
        BtnLog1Layout.setVerticalGroup(
            BtnLog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnLog1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(LableLogBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        Registro.add(BtnLog1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 150, 50));

        ImgBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/undo.png"))); // NOI18N
        ImgBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ImgBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImgBackMouseClicked(evt);
            }
        });
        Registro.add(ImgBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 70, 70));

        TabbedPane.addTab("tab2", Registro);

        Actualizar.setBackground(new java.awt.Color(255, 255, 255));
        Actualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Actualizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImgAct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/loop.png"))); // NOI18N
        Actualizar.add(ImgAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 70, 90));

        LabelSign1.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        LabelSign1.setForeground(new java.awt.Color(51, 51, 51));
        LabelSign1.setText("ACTUALIZAR CONTRASEÑA");
        Actualizar.add(LabelSign1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 470, 40));

        LabelUser2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        LabelUser2.setForeground(new java.awt.Color(51, 51, 51));
        LabelUser2.setText("Usuario");
        Actualizar.add(LabelUser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        usrTxtUpd.setBackground(new java.awt.Color(255, 255, 255));
        usrTxtUpd.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        usrTxtUpd.setForeground(new java.awt.Color(204, 204, 204));
        usrTxtUpd.setText("Ingrese su nombre de usuario.");
        usrTxtUpd.setBorder(null);
        usrTxtUpd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usrTxtUpdMousePressed(evt);
            }
        });
        usrTxtUpd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usrTxtUpdActionPerformed(evt);
            }
        });
        Actualizar.add(usrTxtUpd, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 340, 30));
        Actualizar.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 340, 20));

        BtnLog2.setBackground(new java.awt.Color(255, 210, 12));
        BtnLog2.setForeground(new java.awt.Color(255, 210, 8));
        BtnLog2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnLog2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnLog2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnLog2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnLog2MouseExited(evt);
            }
        });

        LableLogBtn2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        LableLogBtn2.setForeground(new java.awt.Color(0, 0, 0));
        LableLogBtn2.setText("BUSCAR");

        javax.swing.GroupLayout BtnLog2Layout = new javax.swing.GroupLayout(BtnLog2);
        BtnLog2.setLayout(BtnLog2Layout);
        BtnLog2Layout.setHorizontalGroup(
            BtnLog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BtnLog2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(LableLogBtn2)
                .addGap(21, 21, 21))
        );
        BtnLog2Layout.setVerticalGroup(
            BtnLog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnLog2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(LableLogBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        Actualizar.add(BtnLog2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 120, 50));

        ImgBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/undo.png"))); // NOI18N
        ImgBack1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ImgBack1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImgBack1MouseClicked(evt);
            }
        });
        Actualizar.add(ImgBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 70, 70));

        TabbedPane.addTab("tab3", Actualizar);

        Actualizar2.setBackground(new java.awt.Color(255, 255, 255));
        Actualizar2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImgAct2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/loop.png"))); // NOI18N
        Actualizar2.add(ImgAct2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 70, 90));

        LabelSign2.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        LabelSign2.setForeground(new java.awt.Color(51, 51, 51));
        LabelSign2.setText("ACTUALIZAR CONTRASEÑA");
        Actualizar2.add(LabelSign2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 470, 40));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Nueva contraseña:");
        Actualizar2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));
        Actualizar2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 340, 20));

        LabelPass2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        LabelPass2.setForeground(new java.awt.Color(51, 51, 51));
        LabelPass2.setText("Repite la contraseña:");
        Actualizar2.add(LabelPass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, 30));
        Actualizar2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 340, 20));

        BtnUpd2.setBackground(new java.awt.Color(255, 210, 12));
        BtnUpd2.setForeground(new java.awt.Color(255, 210, 8));
        BtnUpd2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnUpd2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnUpd2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnUpd2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnUpd2MouseExited(evt);
            }
        });

        LableUpdBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        LableUpdBtn.setForeground(new java.awt.Color(0, 0, 0));
        LableUpdBtn.setText("   ACTUALIZAR");
        LableUpdBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LableUpdBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LableUpdBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LableUpdBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LableUpdBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LableUpdBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BtnUpd2Layout = new javax.swing.GroupLayout(BtnUpd2);
        BtnUpd2.setLayout(BtnUpd2Layout);
        BtnUpd2Layout.setHorizontalGroup(
            BtnUpd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
            .addGroup(BtnUpd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(LableUpdBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
        );
        BtnUpd2Layout.setVerticalGroup(
            BtnUpd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(BtnUpd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(LableUpdBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );

        Actualizar2.add(BtnUpd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 140, 50));

        ImgBack2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/undo.png"))); // NOI18N
        ImgBack2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ImgBack2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImgBack2MouseClicked(evt);
            }
        });
        Actualizar2.add(ImgBack2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 70, 70));

        nvPass2.setBackground(new java.awt.Color(255, 255, 255));
        nvPass2.setForeground(java.awt.Color.gray);
        nvPass2.setText("********");
        nvPass2.setBorder(null);
        nvPass2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nvPass2MousePressed(evt);
            }
        });
        Actualizar2.add(nvPass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 340, 30));

        nvPass.setBackground(new java.awt.Color(255, 255, 255));
        nvPass.setForeground(java.awt.Color.gray);
        nvPass.setText("********");
        nvPass.setBorder(null);
        nvPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nvPassMousePressed(evt);
            }
        });
        Actualizar2.add(nvPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 340, 30));

        TabbedPane.addTab("tab4", Actualizar2);

        BG.add(TabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 800, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BrraTopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BrraTopMousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_BrraTopMousePressed

    private void BrraTopMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BrraTopMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_BrraTopMouseDragged

    private void PnlCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_PnlCerrarMouseClicked

    private void PnlCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlCerrarMouseEntered
        PnlCerrar.setBackground(Color.red);
        BtnCerrar.setForeground(Color.white);
    }//GEN-LAST:event_PnlCerrarMouseEntered

    private void PnlCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlCerrarMouseExited
        PnlCerrar.setBackground(Color.white);
        BtnCerrar.setForeground(Color.black);
    }//GEN-LAST:event_PnlCerrarMouseExited

    private void BtnLogMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLogMouseEntered
        BtnLog.setBackground(new Color(255, 233, 130));
    }//GEN-LAST:event_BtnLogMouseEntered

    private void BtnLogMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLogMouseExited
        BtnLog.setBackground(new Color(255, 210, 12));
    }//GEN-LAST:event_BtnLogMouseExited

    private void passFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passFieldActionPerformed

    private void userTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTxtMousePressed
        if (userTxt.getText().equals("Ingrese su nombre de usuario.")){
        userTxt.setText("");
        userTxt.setForeground(Color.black);
    }
        if (String.valueOf(passField.getPassword()).isEmpty()){
            passField.setText("********");
            passField.setForeground(Color.lightGray);
        }    
    }//GEN-LAST:event_userTxtMousePressed

    private void passFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passFieldMousePressed
        if (String.valueOf(passField.getPassword()).equals("********")){
        passField.setText("");
        passField.setForeground(Color.black);
    }
        if (userTxt.getText().isEmpty()){
            userTxt.setText("Ingrese su nombre de usuario.");
            userTxt.setForeground(Color.lightGray);
        }
    }//GEN-LAST:event_passFieldMousePressed

    private void SignMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignMouseEntered
        Sign.setForeground(new Color(206, 170, 0));
    }//GEN-LAST:event_SignMouseEntered

    private void SignMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignMouseExited
       Sign.setForeground(Color.black);
    }//GEN-LAST:event_SignMouseExited

    private void OlvPassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OlvPassMouseEntered
        OlvPass.setForeground(new Color(206, 170, 0));
    }//GEN-LAST:event_OlvPassMouseEntered

    private void OlvPassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OlvPassMouseExited
        OlvPass.setForeground(Color.black);
    }//GEN-LAST:event_OlvPassMouseExited

    private void SignMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignMouseClicked
        TabbedPane.setSelectedIndex(1);
    }//GEN-LAST:event_SignMouseClicked

    private void userTxtRMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTxtRMousePressed
        if (userTxtR.getText().equals("Ingrese su nombre de usuario.")){
        userTxtR.setText("");
        userTxtR.setForeground(Color.black);
    }
        if (String.valueOf(passFieldR.getPassword()).isEmpty()){
            passFieldR.setText("********");
            passFieldR.setForeground(Color.lightGray);
        } 
    }//GEN-LAST:event_userTxtRMousePressed

    private void passFieldRMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passFieldRMousePressed
        if (String.valueOf(passFieldR.getPassword()).equals("********")){
        passFieldR.setText("");
        passFieldR.setForeground(Color.black);
    }
        if (userTxtR.getText().isEmpty()){
            userTxtR.setText("Ingrese su nombre de usuario.");
            userTxtR.setForeground(Color.lightGray);
        }
    }//GEN-LAST:event_passFieldRMousePressed

    private void passFieldRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passFieldRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passFieldRActionPerformed

    private void BtnLog1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLog1MouseEntered
         BtnLog1.setBackground(new Color(255, 233, 130));
    }//GEN-LAST:event_BtnLog1MouseEntered

    private void BtnLog1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLog1MouseExited
        BtnLog1.setBackground(new Color(255, 210, 12));
    }//GEN-LAST:event_BtnLog1MouseExited

    private void userTxtRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTxtRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTxtRActionPerformed

    private void usrTxtUpdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usrTxtUpdMousePressed
        if (usrTxtUpd.getText().equals("Ingrese su nombre de usuario.")){
        usrTxtUpd.setText("");
        usrTxtUpd.setForeground(Color.black);
        }    
    }//GEN-LAST:event_usrTxtUpdMousePressed

    private void BtnLog2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLog2MouseEntered
         BtnLog2.setBackground(new Color(255, 233, 130));
    }//GEN-LAST:event_BtnLog2MouseEntered

    private void BtnLog2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLog2MouseExited
        BtnLog2.setBackground(new Color(255, 210, 12));
    }//GEN-LAST:event_BtnLog2MouseExited

    private void usrTxtUpdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usrTxtUpdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usrTxtUpdActionPerformed

    private void OlvPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OlvPassMouseClicked
        TabbedPane.setSelectedIndex(2);
    }//GEN-LAST:event_OlvPassMouseClicked

    private void ImgBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImgBackMouseClicked
        TabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_ImgBackMouseClicked

    private void ImgBack1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImgBack1MouseClicked
        TabbedPane.setSelectedIndex(0);
        usrTxtUpd.setText("Ingrese su nombre de usuario.");
        usrTxtUpd.setForeground(Color.gray);
    }//GEN-LAST:event_ImgBack1MouseClicked

    private void BtnLogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLogMouseClicked
     
//        
//         if(in.consultarUser()==1){
//                  
//            this.dispose();
//            MainLog prueba=new MainLog();
//            prueba.setVisible(true);
//            prueba.setResizable(false);
//            prueba.setLocationRelativeTo(null);
//
//     }else {
//                    
//                    JOptionPane.showMessageDialog(null, "Acceso denegado:\n"
//                    + "Por favor ingrese un usuario y/o contraseña correctos", "Acceso denegado",
//                    JOptionPane.ERROR_MESSAGE);
//            
//     }


            /*this.dispose();
            MainLog prueba=new MainLog();
            prueba.setVisible(true);
            prueba.setResizable(false);
            prueba.setLocationRelativeTo(null);
            userTxt.setText("Ingrese su nombre de usuario.");
            userTxt.setForeground(Color.gray);
            passField.setText("********");
            passField.setForeground(Color.gray);
            
        }else{
            userTxt.setText("Ingrese su nombre de usuario.");
            userTxt.setForeground(Color.gray);
            passField.setText("********");
            passField.setForeground(Color.gray);
            JOptionPane.showMessageDialog(null, "El usuario y la contraseña no exiten, intentalo de nuevo.");
            
        }*/        
    }//GEN-LAST:event_BtnLogMouseClicked

    private void BtnLog1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLog1MouseClicked
        String usuario ="";
        String pass ="";
        
        usuario = userTxtR.getText();
        pass = String.valueOf(passFieldR.getPassword());
        
       boolean resultado;
       resultado=reg.insertarUser(usuario, pass);
        if(resultado==true){
            JOptionPane.showMessageDialog(null, "Fuiste registrado con exito.");
            userTxtR.setText("Ingrese su nombre de usuario.");
            passFieldR.setText("********");
            
        }else{
            JOptionPane.showMessageDialog(null, "No se pudo guardar tu usuario, intentalo de nuevo.");
        }
    }//GEN-LAST:event_BtnLog1MouseClicked

    private void LableLogBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LableLogBtnMouseClicked
        // TODO add your handling code here:
        
        //AQUI VA EL EVENTO DE INICIO DE SESION
        
        if(in.consultarUser(userTxt.getText(), String.valueOf(passField.getPassword()))==1){
                  
            this.dispose();
            MainLog prueba=new MainLog();
            prueba.setVisible(true);
            prueba.setResizable(false);
            prueba.setLocationRelativeTo(null);
            menu.labelUsr.setText(userTxt.getText());
        }else {
                    
            JOptionPane.showMessageDialog(null, "Acceso denegado:\n"
            + "Por favor ingrese un usuario y/o contraseña correctos", "Acceso denegado",
            JOptionPane.ERROR_MESSAGE);
            
        }
        
        
    }//GEN-LAST:event_LableLogBtnMouseClicked

    private void LableLogBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LableLogBtnMouseEntered
        BtnLog.setBackground(new Color(255, 233, 130));
    }//GEN-LAST:event_LableLogBtnMouseEntered

    private void LableLogBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LableLogBtnMouseExited
        BtnLog.setBackground(new Color(255, 210, 12));
    }//GEN-LAST:event_LableLogBtnMouseExited

    private void LableUpdBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LableUpdBtnMouseClicked
        
        String pass1="";
        pass1=String.valueOf(nvPass.getPassword());
        String pass2="";
        pass2=String.valueOf(nvPass2.getPassword());
        String usuario="";
        usuario=usrTxtUpd.getText();
        
        if(pass1.equals(pass2)){
            String pass= pass1;
                if(upd.actualizarPass(usuario, pass)==1){
                    JOptionPane.showMessageDialog(null, "Contraseña cambiada exitosamente.");
                }else {
                    JOptionPane.showMessageDialog(null, "No se pudo cambiar la contraseña.");
                }
        }else{
            JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden.");
            nvPass.setText("");
            nvPass2.setText("");
        }
        
    }//GEN-LAST:event_LableUpdBtnMouseClicked

    private void LableUpdBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LableUpdBtnMouseEntered
        BtnUpd2.setBackground(new Color(255, 233, 130));
    }//GEN-LAST:event_LableUpdBtnMouseEntered

    private void LableUpdBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LableUpdBtnMouseExited
        BtnUpd2.setBackground(new Color(255, 210, 12));
    }//GEN-LAST:event_LableUpdBtnMouseExited

    private void BtnUpd2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnUpd2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnUpd2MouseClicked

    private void BtnUpd2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnUpd2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnUpd2MouseEntered

    private void BtnUpd2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnUpd2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnUpd2MouseExited

    private void ImgBack2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImgBack2MouseClicked
        TabbedPane.setSelectedIndex(0);
        usrTxtUpd.setText("Ingrese su nombre de usuario.");
        usrTxtUpd.setForeground(Color.lightGray);
    }//GEN-LAST:event_ImgBack2MouseClicked

    private void nvPassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nvPassMousePressed
        if (String.valueOf(nvPass2.getPassword()).isEmpty()){
            nvPass2.setText("********");
            nvPass2.setForeground(Color.lightGray);
        } 
        if (String.valueOf(nvPass.getPassword()).equals("********")){
            nvPass.setText("");
            nvPass.setForeground(Color.black);
        }
    }//GEN-LAST:event_nvPassMousePressed

    private void nvPass2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nvPass2MousePressed
        if (String.valueOf(nvPass.getPassword()).isEmpty()){
            nvPass.setText("********");
            nvPass.setForeground(Color.lightGray);
        } 
        if (String.valueOf(nvPass2.getPassword()).equals("********")){
            nvPass2.setText("");
            nvPass2.setForeground(Color.black);
        }
    }//GEN-LAST:event_nvPass2MousePressed

    private void BtnLog2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLog2MouseClicked
        
        String usuario="";
        
        usuario= usrTxtUpd.getText();
        
        if(in.consultarU(usuario)==1){
            TabbedPane.setSelectedIndex(3);
            
        }else{
            JOptionPane.showMessageDialog(null, "No se encontro al usuario en la BDD");
        }   
    }//GEN-LAST:event_BtnLog2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuLog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Actualizar;
    private javax.swing.JPanel Actualizar2;
    private javax.swing.JPanel BG;
    private javax.swing.JPanel BrraTop;
    private javax.swing.JLabel BtnCerrar;
    private javax.swing.JPanel BtnLog;
    private javax.swing.JPanel BtnLog1;
    private javax.swing.JPanel BtnLog2;
    private javax.swing.JPanel BtnUpd2;
    private javax.swing.JLabel ImgAct;
    private javax.swing.JLabel ImgAct2;
    private javax.swing.JLabel ImgBack;
    private javax.swing.JLabel ImgBack1;
    private javax.swing.JLabel ImgBack2;
    private javax.swing.JLabel ImgLog;
    private javax.swing.JLabel ImgSign;
    private javax.swing.JPanel Inicio;
    private javax.swing.JLabel LabelLog;
    private javax.swing.JLabel LabelPass;
    private javax.swing.JLabel LabelPass1;
    private javax.swing.JLabel LabelPass2;
    private javax.swing.JLabel LabelSign;
    private javax.swing.JLabel LabelSign1;
    private javax.swing.JLabel LabelSign2;
    private javax.swing.JLabel LabelUser;
    private javax.swing.JLabel LabelUser1;
    private javax.swing.JLabel LabelUser2;
    private javax.swing.JLabel LableLogBtn;
    private javax.swing.JLabel LableLogBtn1;
    private javax.swing.JLabel LableLogBtn2;
    private javax.swing.JLabel LableUpdBtn;
    private javax.swing.JLabel OlvPass;
    private javax.swing.JPanel PnlCerrar;
    private javax.swing.JPanel Registro;
    private javax.swing.JLabel Sign;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JLabel imgLog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JPasswordField nvPass;
    private javax.swing.JPasswordField nvPass2;
    public static javax.swing.JPasswordField passField;
    private javax.swing.JPasswordField passFieldR;
    public static javax.swing.JTextField userTxt;
    private javax.swing.JTextField userTxtR;
    private javax.swing.JTextField usrTxtUpd;
    // End of variables declaration//GEN-END:variables
}
