package com.views;
import com.basedd.*;
import static com.views.MenuLog.passField;
import static com.views.MenuLog.userTxt;
import java.awt.*;
import java.sql.*;
import javax.swing.*;
/* @ChemaPF */

public class viewAlumnos extends javax.swing.JFrame {

    int xMouse, yMouse; 
    MainLog menu;
    RegistroBD reg;
    EliminarBD el;
    ActualizarBD upd;
    InicioBD in;
    
    public viewAlumnos() {
        initComponents();
        menu = new MainLog();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BrraTop = new javax.swing.JPanel();
        PnlMenu = new javax.swing.JPanel();
        BtnMenu = new javax.swing.JLabel();
        PnlCerrar = new javax.swing.JPanel();
        BtnCerrar = new javax.swing.JLabel();
        TabbedA = new javax.swing.JTabbedPane();
        BGMA = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelAU = new javax.swing.JPanel();
        btnAU = new javax.swing.JLabel();
        panelAA = new javax.swing.JPanel();
        btnAA = new javax.swing.JLabel();
        panelAE = new javax.swing.JPanel();
        btnAD = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        BGIA = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMatriR = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txtNomR = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        txtMaR = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        btnRA = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnMA = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtIDU = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        BGEA = new javax.swing.JPanel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtMatriE = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        btnEA = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btnMA1 = new javax.swing.JLabel();
        BGAA = new javax.swing.JPanel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtMatriA = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        txtNomA = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        txtMaA = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        btnAAL = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        btnMA2 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtIDUA = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        BGAA1 = new javax.swing.JPanel();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtMatriA1 = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        btnBA = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        btnMA3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BrraTop.setBackground(new java.awt.Color(255, 255, 255));
        BrraTop.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BrraTopMouseDragged(evt);
            }
        });
        BrraTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BrraTopMousePressed(evt);
            }
        });

        PnlMenu.setBackground(new java.awt.Color(255, 255, 255));
        PnlMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PnlMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PnlMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PnlMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PnlMenuMouseExited(evt);
            }
        });
        PnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnMenu.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BtnMenu.setForeground(new java.awt.Color(0, 0, 0));
        BtnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/hogar.png"))); // NOI18N
        BtnMenu.setText("X");
        PnlMenu.add(BtnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 32, 40));

        PnlCerrar.setBackground(new java.awt.Color(255, 255, 255));
        PnlCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PnlCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PnlCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PnlCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PnlCerrarMouseExited(evt);
            }
        });
        PnlCerrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnCerrar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BtnCerrar.setForeground(new java.awt.Color(0, 0, 0));
        BtnCerrar.setText("X");
        PnlCerrar.add(BtnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 32, 40));

        javax.swing.GroupLayout BrraTopLayout = new javax.swing.GroupLayout(BrraTop);
        BrraTop.setLayout(BrraTopLayout);
        BrraTopLayout.setHorizontalGroup(
            BrraTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BrraTopLayout.createSequentialGroup()
                .addComponent(PnlCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 446, Short.MAX_VALUE))
            .addGroup(BrraTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BrraTopLayout.createSequentialGroup()
                    .addContainerGap(32, Short.MAX_VALUE)
                    .addComponent(PnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(398, Short.MAX_VALUE)))
        );
        BrraTopLayout.setVerticalGroup(
            BrraTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BrraTopLayout.createSequentialGroup()
                .addComponent(PnlCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
            .addGroup(BrraTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(BrraTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 40));

        BGMA.setBackground(new java.awt.Color(255, 255, 255));
        BGMA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/graduate.png"))); // NOI18N
        BGMA.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 70, 80));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("ALUMNOS");
        BGMA.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        panelAU.setBackground(java.awt.Color.orange);
        panelAU.setForeground(java.awt.Color.orange);
        panelAU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelAU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelAUMouseEntered(evt);
            }
        });
        panelAU.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAU.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAU.setForeground(new java.awt.Color(51, 51, 51));
        btnAU.setText("     ACTUALIZAR");
        btnAU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAUMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAUMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAUMouseExited(evt);
            }
        });
        panelAU.add(btnAU, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 70));

        BGMA.add(panelAU, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 160, 70));

        panelAA.setBackground(java.awt.Color.orange);
        panelAA.setForeground(java.awt.Color.orange);
        panelAA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelAA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelAAMouseEntered(evt);
            }
        });
        panelAA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAA.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAA.setForeground(new java.awt.Color(51, 51, 51));
        btnAA.setText("        AGREGAR");
        btnAA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAAMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAAMouseExited(evt);
            }
        });
        panelAA.add(btnAA, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 1, 170, 70));

        BGMA.add(panelAA, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 160, 70));

        panelAE.setBackground(java.awt.Color.orange);
        panelAE.setForeground(java.awt.Color.orange);
        panelAE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelAE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelAEMouseEntered(evt);
            }
        });
        panelAE.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAD.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAD.setForeground(new java.awt.Color(51, 51, 51));
        btnAD.setText("        ELIMINAR");
        btnAD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnADMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnADMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnADMouseExited(evt);
            }
        });
        panelAE.add(btnAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 70));

        BGMA.add(panelAE, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 160, 70));
        BGMA.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 310, 10));

        TabbedA.addTab("tab1", BGMA);

        BGIA.setBackground(new java.awt.Color(255, 255, 255));
        BGIA.setForeground(new java.awt.Color(255, 255, 255));
        BGIA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        BGIA.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 310, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("REGISTRAR ALUMNO");
        BGIA.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/graduate.png"))); // NOI18N
        BGIA.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 70, 80));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Matrícula del alumno:");
        BGIA.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        txtMatriR.setBackground(new java.awt.Color(255, 255, 255));
        txtMatriR.setForeground(java.awt.Color.lightGray);
        txtMatriR.setText("Ingrese la nueva matricula");
        txtMatriR.setBorder(null);
        txtMatriR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtMatriRMousePressed(evt);
            }
        });
        txtMatriR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatriRActionPerformed(evt);
            }
        });
        BGIA.add(txtMatriR, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 310, 30));
        BGIA.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 310, 10));

        txtNomR.setBackground(new java.awt.Color(255, 255, 255));
        txtNomR.setForeground(java.awt.Color.lightGray);
        txtNomR.setText("Ingrese el nombre del nuevo alumno");
        txtNomR.setBorder(null);
        txtNomR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNomRMousePressed(evt);
            }
        });
        txtNomR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomRActionPerformed(evt);
            }
        });
        BGIA.add(txtNomR, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 310, 30));
        BGIA.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 310, 10));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Nombre del alumno:");
        BGIA.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        txtMaR.setBackground(new java.awt.Color(255, 255, 255));
        txtMaR.setForeground(java.awt.Color.lightGray);
        txtMaR.setText("Ingrese el ID de la materia que llevara el alumno");
        txtMaR.setBorder(null);
        txtMaR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtMaRMousePressed(evt);
            }
        });
        txtMaR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaRActionPerformed(evt);
            }
        });
        BGIA.add(txtMaR, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 310, 30));
        BGIA.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 310, 10));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Materia que llevara el alumno:");
        BGIA.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        btnRA.setBackground(java.awt.Color.orange);
        btnRA.setForeground(java.awt.Color.orange);
        btnRA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("        REGISTRAR");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        btnRA.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 40));

        BGIA.add(btnRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 540, 140, 40));

        btnMA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/angle-left.png"))); // NOI18N
        btnMA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMAMouseClicked(evt);
            }
        });
        BGIA.add(btnMA, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 40, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("ID del usuario:");
        BGIA.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        txtIDU.setBackground(new java.awt.Color(255, 255, 255));
        txtIDU.setForeground(java.awt.Color.lightGray);
        txtIDU.setText("*Recurda que el ID ya debe estar creado*");
        txtIDU.setBorder(null);
        txtIDU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtIDUMousePressed(evt);
            }
        });
        txtIDU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDUActionPerformed(evt);
            }
        });
        BGIA.add(txtIDU, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 310, 30));
        BGIA.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, 310, 10));

        TabbedA.addTab("tab2", BGIA);

        BGEA.setBackground(new java.awt.Color(255, 255, 255));
        BGEA.setForeground(new java.awt.Color(255, 255, 255));
        BGEA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        BGEA.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 310, 10));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("ELIMINAR ALUMNO");
        BGEA.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/graduate.png"))); // NOI18N
        BGEA.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 70, 80));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Matrícula del alumno:");
        BGEA.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        txtMatriE.setBackground(new java.awt.Color(255, 255, 255));
        txtMatriE.setForeground(java.awt.Color.lightGray);
        txtMatriE.setText("Ingrese la matricula del alumno a eliminar");
        txtMatriE.setBorder(null);
        txtMatriE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtMatriEMousePressed(evt);
            }
        });
        txtMatriE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatriEActionPerformed(evt);
            }
        });
        BGEA.add(txtMatriE, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 310, 30));
        BGEA.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 310, 10));

        btnEA.setBackground(java.awt.Color.orange);
        btnEA.setForeground(java.awt.Color.orange);
        btnEA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("          ELIMINAR");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel15MouseExited(evt);
            }
        });
        btnEA.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 40));

        BGEA.add(btnEA, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 540, 140, 40));

        btnMA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/angle-left.png"))); // NOI18N
        btnMA1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMA1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMA1MouseClicked(evt);
            }
        });
        BGEA.add(btnMA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 40, 40));

        TabbedA.addTab("tab2", BGEA);

        BGAA.setBackground(new java.awt.Color(255, 255, 255));
        BGAA.setForeground(new java.awt.Color(255, 255, 255));
        BGAA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        BGAA.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 310, 10));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("ACTUALIZAR ALUMNO");
        BGAA.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/graduate.png"))); // NOI18N
        BGAA.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 70, 80));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Ingresa los nuevos datos del alumno");
        BGAA.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        txtMatriA.setBackground(new java.awt.Color(255, 255, 255));
        txtMatriA.setForeground(java.awt.Color.lightGray);
        txtMatriA.setText("Ingrese la nueva matricula");
        txtMatriA.setBorder(null);
        txtMatriA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtMatriAMousePressed(evt);
            }
        });
        txtMatriA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatriAActionPerformed(evt);
            }
        });
        BGAA.add(txtMatriA, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 310, 30));
        BGAA.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 310, 10));

        txtNomA.setBackground(new java.awt.Color(255, 255, 255));
        txtNomA.setForeground(java.awt.Color.lightGray);
        txtNomA.setText("Ingrese el nombre del nuevo alumno");
        txtNomA.setBorder(null);
        txtNomA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNomAMousePressed(evt);
            }
        });
        txtNomA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomAActionPerformed(evt);
            }
        });
        BGAA.add(txtNomA, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 310, 30));
        BGAA.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 310, 10));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Nombre del alumno:");
        BGAA.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        txtMaA.setBackground(new java.awt.Color(255, 255, 255));
        txtMaA.setForeground(java.awt.Color.lightGray);
        txtMaA.setText("Ingrese el ID de la materia que llevara el alumno");
        txtMaA.setBorder(null);
        txtMaA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtMaAMousePressed(evt);
            }
        });
        txtMaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaAActionPerformed(evt);
            }
        });
        BGAA.add(txtMaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 310, 30));
        BGAA.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 310, 10));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("Materia que llevara el alumno:");
        BGAA.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        btnAAL.setBackground(java.awt.Color.orange);
        btnAAL.setForeground(java.awt.Color.orange);
        btnAAL.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAAL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("       ACTUALIZAR");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel19MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel19MouseExited(evt);
            }
        });
        btnAAL.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 40));

        BGAA.add(btnAAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 540, 140, 40));

        btnMA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/angle-left.png"))); // NOI18N
        btnMA2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMA2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMA2MouseClicked(evt);
            }
        });
        BGAA.add(btnMA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 40, 40));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setText("ID del usuario:");
        BGAA.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        txtIDUA.setBackground(new java.awt.Color(255, 255, 255));
        txtIDUA.setForeground(java.awt.Color.lightGray);
        txtIDUA.setText("*Recurda que el ID ya debe estar creado*");
        txtIDUA.setBorder(null);
        txtIDUA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtIDUAMousePressed(evt);
            }
        });
        txtIDUA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDUAActionPerformed(evt);
            }
        });
        BGAA.add(txtIDUA, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 310, 30));
        BGAA.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, 310, 10));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setText("Matrícula del alumno:");
        BGAA.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        TabbedA.addTab("tab2", BGAA);

        BGAA1.setBackground(new java.awt.Color(255, 255, 255));
        BGAA1.setForeground(new java.awt.Color(255, 255, 255));
        BGAA1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        BGAA1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 310, 10));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText("BUSCAR ALUMNO");
        BGAA1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/graduate.png"))); // NOI18N
        BGAA1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 70, 80));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setText("Matrícula del alumno:");
        BGAA1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        txtMatriA1.setBackground(new java.awt.Color(255, 255, 255));
        txtMatriA1.setForeground(java.awt.Color.lightGray);
        txtMatriA1.setText("Ingrese la matricula del alumno");
        txtMatriA1.setBorder(null);
        txtMatriA1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtMatriA1MousePressed(evt);
            }
        });
        txtMatriA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatriA1ActionPerformed(evt);
            }
        });
        BGAA1.add(txtMatriA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 310, 30));
        BGAA1.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 310, 10));

        btnBA.setBackground(java.awt.Color.orange);
        btnBA.setForeground(java.awt.Color.orange);
        btnBA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setText("          BUSCAR");
        jLabel25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel25MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel25MouseExited(evt);
            }
        });
        btnBA.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 40));

        BGAA1.add(btnBA, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 540, 140, 40));

        btnMA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/angle-left.png"))); // NOI18N
        btnMA3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMA3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMA3MouseClicked(evt);
            }
        });
        BGAA1.add(btnMA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 40, 40));

        TabbedA.addTab("tab2", BGAA1);

        getContentPane().add(TabbedA, new org.netbeans.lib.awtextra.AbsoluteConstraints(-14, -39, 500, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PnlCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_PnlCerrarMouseClicked

    private void PnlCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlCerrarMouseEntered
        PnlCerrar.setBackground(Color.red);
        BtnCerrar.setForeground(Color.white);
    }//GEN-LAST:event_PnlCerrarMouseEntered

    private void PnlCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlCerrarMouseExited
        PnlCerrar.setBackground(Color.white);
        BtnCerrar.setForeground(Color.black);
    }//GEN-LAST:event_PnlCerrarMouseExited

    private void BrraTopMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BrraTopMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_BrraTopMouseDragged

    private void BrraTopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BrraTopMousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_BrraTopMousePressed

    private void PnlMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlMenuMouseClicked
        this.dispose();
        menu.setVisible(true);
        menu.setResizable(false);
        menu.setLocationRelativeTo(null);
    }//GEN-LAST:event_PnlMenuMouseClicked

    private void PnlMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlMenuMouseEntered
        PnlMenu.setBackground(Color.blue);
    }//GEN-LAST:event_PnlMenuMouseEntered

    private void PnlMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlMenuMouseExited
        PnlMenu.setBackground(Color.white);
    }//GEN-LAST:event_PnlMenuMouseExited

    private void txtIDUAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDUAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDUAActionPerformed

    private void txtIDUAMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIDUAMousePressed
        if (txtIDUA.getText().equals("*Recurda que el ID ya debe estar creado*")){
            txtIDUA.setText("");
            txtIDUA.setForeground(Color.black);
        }
        if (txtNomA.getText().isEmpty()){
            txtNomA.setText("Ingrese el nombre del nuevo alumno");
            txtNomA.setForeground(Color.lightGray);
        }
        if (txtMatriA.getText().isEmpty()){
            txtMatriA.setText("Ingrese la nueva matricula");
            txtMatriA.setForeground(Color.lightGray);
        }
        if (txtMaA.getText().isEmpty()){
            txtMaA.setText("Ingrese el ID de la materia que llevara el alumno");
            txtMaA.setForeground(Color.lightGray);
        }
    }//GEN-LAST:event_txtIDUAMousePressed

    private void btnMA2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMA2MouseClicked
        TabbedA.setSelectedIndex(0);
    }//GEN-LAST:event_btnMA2MouseClicked

    private void jLabel19MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseExited
        btnAAL.setBackground(Color.orange);
    }//GEN-LAST:event_jLabel19MouseExited

    private void jLabel19MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseEntered
        btnAAL.setBackground(new Color(255, 152, 20));
    }//GEN-LAST:event_jLabel19MouseEntered

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        String matricula=txtMatriA1.getText();
        String matriculaN="";
        String nombre="";
        String id_m="";
        String id_u="";

        reg=new RegistroBD();
        upd=new ActualizarBD();
        matriculaN=txtMatriA.getText();
        nombre=txtNomA.getText();
        id_m=txtMaA.getText();
        id_u=txtIDUA.getText();

        if(upd.actualizarAlumno(matricula, matriculaN, nombre, id_u, id_m)==1){
            JOptionPane.showMessageDialog(null, "Los datos se actualizaron correctamente");
            txtMatriA.setText("Ingrese la nueva matricula");
            txtMatriA.setForeground(Color.lightGray);
            txtNomA.setText("Ingrese el nombre del nuevo alumno");
            txtNomA.setForeground(Color.lightGray);
            txtMaA.setText("Ingrese el ID de la materia que llevara el alumno");
            txtMaA.setForeground(Color.lightGray);
            txtIDUA.setText("*Recurda que el ID ya debe estar creado*");
            txtIDUA.setForeground(Color.lightGray);
        }else{
            JOptionPane.showMessageDialog(null, "Hubo un error para actualizar los datos");

        }

    }//GEN-LAST:event_jLabel19MouseClicked

    private void txtMaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaAActionPerformed

    private void txtMaAMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMaAMousePressed
        if (txtMaA.getText().equals("Ingrese el ID de la materia que llevara el alumno")){
            txtMaA.setText("");
            txtMaA.setForeground(Color.black);
        }
        if (txtNomA.getText().isEmpty()){
            txtNomA.setText("Ingrese el nombre del nuevo alumno");
            txtNomA.setForeground(Color.lightGray);
        }
        if (txtMatriA.getText().isEmpty()){
            txtMatriA.setText("Ingrese la nueva matricula");
            txtMatriA.setForeground(Color.lightGray);
        }
        if (txtIDUA.getText().isEmpty()){
            txtIDUA.setText("*Recurda que el ID ya debe estar creado*");
            txtIDUA.setForeground(Color.lightGray);
        }
    }//GEN-LAST:event_txtMaAMousePressed

    private void txtNomAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomAActionPerformed

    private void txtNomAMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNomAMousePressed
        if (txtNomA.getText().equals("Ingrese el nombre del nuevo alumno")){
            txtNomA.setText("");
            txtNomA.setForeground(Color.black);
        }
        if (txtMatriA.getText().isEmpty()){
            txtMatriA.setText("Ingrese la nueva matricula");
            txtMatriA.setForeground(Color.lightGray);
        }
        if (txtMaA.getText().isEmpty()){
            txtMaA.setText("Ingrese el ID de la materia que llevara el alumno");
            txtMaA.setForeground(Color.lightGray);
        }
        if (txtIDUA.getText().isEmpty()){
            txtIDUA.setText("*Recurda que el ID ya debe estar creado*");
            txtIDUA.setForeground(Color.lightGray);
        }
    }//GEN-LAST:event_txtNomAMousePressed

    private void txtMatriAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatriAActionPerformed

    private void txtMatriAMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMatriAMousePressed
        if (txtMatriA.getText().equals("Ingrese la nueva matricula")){
            txtMatriA.setText("");
            txtMatriA.setForeground(Color.black);
        }
        if (txtNomA.getText().isEmpty()){
            txtNomA.setText("Ingrese el nombre del nuevo alumno");
            txtNomA.setForeground(Color.lightGray);
        }
        if (txtMaA.getText().isEmpty()){
            txtMaA.setText("Ingrese el ID de la materia que llevara el alumno");
            txtMaA.setForeground(Color.lightGray);
        }
        if (txtIDUA.getText().isEmpty()){
            txtIDUA.setText("*Recurda que el ID ya debe estar creado*");
            txtIDUA.setForeground(Color.lightGray);
        }
    }//GEN-LAST:event_txtMatriAMousePressed

    private void btnMA1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMA1MouseClicked
        TabbedA.setSelectedIndex(0);
    }//GEN-LAST:event_btnMA1MouseClicked

    private void jLabel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseExited
        btnEA.setBackground(Color.orange);
    }//GEN-LAST:event_jLabel15MouseExited

    private void jLabel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseEntered
        btnEA.setBackground(new Color(255, 152, 20));
    }//GEN-LAST:event_jLabel15MouseEntered

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked

        el=new EliminarBD();
        String matricula=txtMatriE.getText();
        if(el.eliminarAlumno(matricula)==1){
            JOptionPane.showMessageDialog(null, "El alumno fue eliminado con exito.");
            txtMatriE.setText("Ingrese la matricula del alumno a eliminar");
            txtMatriE.setForeground(Color.lightGray);
        }else{
            JOptionPane.showMessageDialog(null, "No se pudo eliminar el usuario.");
        }

    }//GEN-LAST:event_jLabel15MouseClicked

    private void txtMatriEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatriEActionPerformed

    private void txtMatriEMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMatriEMousePressed
        if (txtMatriE.getText().equals("Ingrese la matricula del alumno a eliminar")){
            txtMatriE.setText("");
            txtMatriE.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtMatriEMousePressed

    private void txtIDUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDUActionPerformed

    private void txtIDUMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIDUMousePressed
        if (txtIDU.getText().equals("*Recurda que el ID ya debe estar creado*")){
            txtIDU.setText("");
            txtIDU.setForeground(Color.black);
        }
        if (txtNomR.getText().isEmpty()){
            txtNomR.setText("Ingrese el nombre del nuevo alumno");
            txtNomR.setForeground(Color.lightGray);
        }
        if (txtMatriR.getText().isEmpty()){
            txtMatriR.setText("Ingrese la nueva matricula");
            txtMatriR.setForeground(Color.lightGray);
        }
        if (txtMaR.getText().isEmpty()){
            txtMaR.setText("Ingrese el ID de la materia que llevara el alumno");
            txtMaR.setForeground(Color.lightGray);
        }
    }//GEN-LAST:event_txtIDUMousePressed

    private void btnMAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMAMouseClicked
        TabbedA.setSelectedIndex(0);
    }//GEN-LAST:event_btnMAMouseClicked

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        btnRA.setBackground(Color.orange);
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        btnRA.setBackground(new Color(255, 152, 20));
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        String matricula="";
        String nombre="";
        String id_m="";
        String id_u="";

        reg=new RegistroBD();
        matricula=txtMatriR.getText();
        nombre=txtNomR.getText();
        id_m=txtMaR.getText();
        id_u=txtIDU.getText();

        boolean resultado;
        resultado=reg.insertarAlumno(matricula, nombre, id_u, id_m);
        if(resultado==true){
            JOptionPane.showMessageDialog(null, "El alumno fue registrado con exito.");
            txtMatriR.setText("Ingrese la nueva matricula");
            txtNomR.setText("Ingrese el nombre del nuevo alumno");
            txtMaR.setText("Ingrese el ID de la materia que llevara el alumno");
            txtIDU.setText("*Recurda que el ID ya debe estar creado*");

        }else{
            JOptionPane.showMessageDialog(null, "No se pudo guardar tu usuario, intentalo de nuevo.");
        }

    }//GEN-LAST:event_jLabel8MouseClicked

    private void txtMaRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaRActionPerformed

    private void txtMaRMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMaRMousePressed
        if (txtMaR.getText().equals("Ingrese el ID de la materia que llevara el alumno")){
            txtMaR.setText("");
            txtMaR.setForeground(Color.black);
        }
        if (txtNomR.getText().isEmpty()){
            txtNomR.setText("Ingrese el nombre del nuevo alumno");
            txtNomR.setForeground(Color.lightGray);
        }
        if (txtMatriR.getText().isEmpty()){
            txtMatriR.setText("Ingrese la nueva matricula");
            txtMatriR.setForeground(Color.lightGray);
        }
        if (txtIDU.getText().isEmpty()){
            txtIDU.setText("*Recurda que el ID ya debe estar creado*");
            txtIDU.setForeground(Color.lightGray);
        }
    }//GEN-LAST:event_txtMaRMousePressed

    private void txtNomRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomRActionPerformed

    private void txtNomRMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNomRMousePressed
        if (txtNomR.getText().equals("Ingrese el nombre del nuevo alumno")){
            txtNomR.setText("");
            txtNomR.setForeground(Color.black);
        }
        if (txtMatriR.getText().isEmpty()){
            txtMatriR.setText("Ingrese la nueva matricula");
            txtMatriR.setForeground(Color.lightGray);
        }
        if (txtMaR.getText().isEmpty()){
            txtMaR.setText("Ingrese el ID de la materia que llevara el alumno");
            txtMaR.setForeground(Color.lightGray);
        }
        if (txtIDU.getText().isEmpty()){
            txtIDU.setText("*Recurda que el ID ya debe estar creado*");
            txtIDU.setForeground(Color.lightGray);
        }
    }//GEN-LAST:event_txtNomRMousePressed

    private void txtMatriRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatriRActionPerformed

    private void txtMatriRMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMatriRMousePressed
        if (txtMatriR.getText().equals("Ingrese la nueva matricula")){
            txtMatriR.setText("");
            txtMatriR.setForeground(Color.black);
        }
        if (txtNomR.getText().isEmpty()){
            txtNomR.setText("Ingrese el nombre del nuevo alumno");
            txtNomR.setForeground(Color.lightGray);
        }
        if (txtMaR.getText().isEmpty()){
            txtMaR.setText("Ingrese el ID de la materia que llevara el alumno");
            txtMaR.setForeground(Color.lightGray);
        }
        if (txtIDU.getText().isEmpty()){
            txtIDU.setText("*Recurda que el ID ya debe estar creado*");
            txtIDU.setForeground(Color.lightGray);
        }

    }//GEN-LAST:event_txtMatriRMousePressed

    private void panelAEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAEMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelAEMouseEntered

    private void btnADMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnADMouseExited
        panelAE.setBackground(new Color(255, 200, 0));
    }//GEN-LAST:event_btnADMouseExited

    private void btnADMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnADMouseEntered
        panelAE.setBackground(new Color(255, 152, 20));
    }//GEN-LAST:event_btnADMouseEntered

    private void btnADMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnADMouseClicked
        TabbedA.setSelectedIndex(2);
    }//GEN-LAST:event_btnADMouseClicked

    private void panelAAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAAMouseEntered
        panelAA.setBackground(new Color(255, 152,20));
    }//GEN-LAST:event_panelAAMouseEntered

    private void btnAAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAAMouseExited
        panelAA.setBackground(new Color(255, 200, 0));
    }//GEN-LAST:event_btnAAMouseExited

    private void btnAAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAAMouseEntered
        panelAA.setBackground(new Color(255, 152,20));
    }//GEN-LAST:event_btnAAMouseEntered

    private void btnAAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAAMouseClicked
        TabbedA.setSelectedIndex(1);
    }//GEN-LAST:event_btnAAMouseClicked

    private void panelAUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAUMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelAUMouseEntered

    private void btnAUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAUMouseExited
        panelAU.setBackground(new Color(255, 200, 0));
    }//GEN-LAST:event_btnAUMouseExited

    private void btnAUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAUMouseEntered
        panelAU.setBackground(new Color(255, 152,20));
    }//GEN-LAST:event_btnAUMouseEntered

    private void btnAUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAUMouseClicked
        TabbedA.setSelectedIndex(4);
    }//GEN-LAST:event_btnAUMouseClicked

    private void txtMatriA1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMatriA1MousePressed
        if (txtMatriA1.getText().equals("Ingrese la matricula del alumno")){
            txtMatriA1.setText("");
            txtMatriA1.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtMatriA1MousePressed

    private void txtMatriA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatriA1ActionPerformed

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        String matricula="";

        in=new InicioBD();
        matricula=txtMatriA1.getText();
       

        if(in.consultarAlumno(matricula)==1){
            TabbedA.setSelectedIndex(3);
        }else{
            JOptionPane.showMessageDialog(null, "Hubo un error para encontrar al alumno");

        }
        
    }//GEN-LAST:event_jLabel25MouseClicked

    private void jLabel25MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseEntered
        btnBA.setBackground(new Color(255, 152, 20));
    }//GEN-LAST:event_jLabel25MouseEntered

    private void jLabel25MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseExited
        btnBA.setBackground(Color.orange);
    }//GEN-LAST:event_jLabel25MouseExited

    private void btnMA3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMA3MouseClicked
        TabbedA.setSelectedIndex(0);
    }//GEN-LAST:event_btnMA3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewAlumnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BGAA;
    private javax.swing.JPanel BGAA1;
    private javax.swing.JPanel BGEA;
    private javax.swing.JPanel BGIA;
    private javax.swing.JPanel BGMA;
    private javax.swing.JPanel BrraTop;
    private javax.swing.JLabel BtnCerrar;
    private javax.swing.JLabel BtnMenu;
    private javax.swing.JPanel PnlCerrar;
    private javax.swing.JPanel PnlMenu;
    private javax.swing.JTabbedPane TabbedA;
    private javax.swing.JLabel btnAA;
    private javax.swing.JPanel btnAAL;
    private javax.swing.JLabel btnAD;
    private javax.swing.JLabel btnAU;
    private javax.swing.JPanel btnBA;
    private javax.swing.JPanel btnEA;
    private javax.swing.JLabel btnMA;
    private javax.swing.JLabel btnMA1;
    private javax.swing.JLabel btnMA2;
    private javax.swing.JLabel btnMA3;
    private javax.swing.JPanel btnRA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JPanel panelAA;
    private javax.swing.JPanel panelAE;
    private javax.swing.JPanel panelAU;
    private javax.swing.JTextField txtIDU;
    private javax.swing.JTextField txtIDUA;
    private javax.swing.JTextField txtMaA;
    private javax.swing.JTextField txtMaR;
    private javax.swing.JTextField txtMatriA;
    private javax.swing.JTextField txtMatriA1;
    private javax.swing.JTextField txtMatriE;
    private javax.swing.JTextField txtMatriR;
    private javax.swing.JTextField txtNomA;
    private javax.swing.JTextField txtNomR;
    // End of variables declaration//GEN-END:variables
}
