package com.views;

import com.basedd.*;
import static com.views.MenuLog.passField;
import static com.views.MenuLog.userTxt;
import java.awt.*;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @ChemaPF
 */
public class viewMaterias extends javax.swing.JFrame {

    int xMouse, yMouse; 
    MainLog menu;
    RegistroBD reg;
    EliminarBD el;
    ActualizarBD upd;
    InicioBD in;
    
    public viewMaterias() {
        initComponents();
        menu = new MainLog();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BrraTop = new javax.swing.JPanel();
        PnlMenu = new javax.swing.JPanel();
        BtnMenu = new javax.swing.JLabel();
        PnlCerrar = new javax.swing.JPanel();
        BtnCerrar = new javax.swing.JLabel();
        TabbedM = new javax.swing.JTabbedPane();
        BGMM = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelAU = new javax.swing.JPanel();
        btnAU = new javax.swing.JLabel();
        panelAA = new javax.swing.JPanel();
        btnAA = new javax.swing.JLabel();
        panelAE = new javax.swing.JPanel();
        btnAD = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        BGIM = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIMR = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txtNomR = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        btnRA = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnMA = new javax.swing.JLabel();
        BGEM = new javax.swing.JPanel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtMatriE = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        btnEA = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btnMA1 = new javax.swing.JLabel();
        BGAM = new javax.swing.JPanel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtIA = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        txtNomA = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        btnAAL = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        btnMA2 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        BGAM1 = new javax.swing.JPanel();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtIA1 = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        btnBA = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        btnMA3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BrraTop.setBackground(new java.awt.Color(255, 255, 255));
        BrraTop.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BrraTopMouseDragged(evt);
            }
        });
        BrraTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BrraTopMousePressed(evt);
            }
        });

        PnlMenu.setBackground(new java.awt.Color(255, 255, 255));
        PnlMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PnlMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PnlMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PnlMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PnlMenuMouseExited(evt);
            }
        });
        PnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnMenu.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BtnMenu.setForeground(new java.awt.Color(0, 0, 0));
        BtnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/hogar.png"))); // NOI18N
        BtnMenu.setText("X");
        PnlMenu.add(BtnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 32, 40));

        PnlCerrar.setBackground(new java.awt.Color(255, 255, 255));
        PnlCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PnlCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PnlCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PnlCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PnlCerrarMouseExited(evt);
            }
        });
        PnlCerrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnCerrar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BtnCerrar.setForeground(new java.awt.Color(0, 0, 0));
        BtnCerrar.setText("X");
        PnlCerrar.add(BtnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 32, 40));

        javax.swing.GroupLayout BrraTopLayout = new javax.swing.GroupLayout(BrraTop);
        BrraTop.setLayout(BrraTopLayout);
        BrraTopLayout.setHorizontalGroup(
            BrraTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BrraTopLayout.createSequentialGroup()
                .addComponent(PnlCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 446, Short.MAX_VALUE))
            .addGroup(BrraTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BrraTopLayout.createSequentialGroup()
                    .addContainerGap(32, Short.MAX_VALUE)
                    .addComponent(PnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(398, Short.MAX_VALUE)))
        );
        BrraTopLayout.setVerticalGroup(
            BrraTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BrraTopLayout.createSequentialGroup()
                .addComponent(PnlCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
            .addGroup(BrraTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(BrraTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 40));

        BGMM.setBackground(new java.awt.Color(255, 255, 255));
        BGMM.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/book (1).png"))); // NOI18N
        BGMM.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 70, 80));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("MATERIAS");
        BGMM.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        panelAU.setBackground(java.awt.Color.orange);
        panelAU.setForeground(java.awt.Color.orange);
        panelAU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelAU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelAUMouseEntered(evt);
            }
        });
        panelAU.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAU.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAU.setForeground(new java.awt.Color(51, 51, 51));
        btnAU.setText("     ACTUALIZAR");
        btnAU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAUMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAUMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAUMouseExited(evt);
            }
        });
        panelAU.add(btnAU, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 70));

        BGMM.add(panelAU, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 160, 70));

        panelAA.setBackground(java.awt.Color.orange);
        panelAA.setForeground(java.awt.Color.orange);
        panelAA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelAA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelAAMouseEntered(evt);
            }
        });
        panelAA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAA.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAA.setForeground(new java.awt.Color(51, 51, 51));
        btnAA.setText("        AGREGAR");
        btnAA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAAMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAAMouseExited(evt);
            }
        });
        panelAA.add(btnAA, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 1, 170, 70));

        BGMM.add(panelAA, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 160, 70));

        panelAE.setBackground(java.awt.Color.orange);
        panelAE.setForeground(java.awt.Color.orange);
        panelAE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelAE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelAEMouseEntered(evt);
            }
        });
        panelAE.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAD.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAD.setForeground(new java.awt.Color(51, 51, 51));
        btnAD.setText("        ELIMINAR");
        btnAD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnADMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnADMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnADMouseExited(evt);
            }
        });
        panelAE.add(btnAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 70));

        BGMM.add(panelAE, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 160, 70));
        BGMM.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 310, 10));

        TabbedM.addTab("tab1", BGMM);

        BGIM.setBackground(new java.awt.Color(255, 255, 255));
        BGIM.setForeground(new java.awt.Color(255, 255, 255));
        BGIM.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        BGIM.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 310, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("REGISTRAR MATERIA");
        BGIM.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/book (1).png"))); // NOI18N
        BGIM.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 70, 80));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("ID de la materia:");
        BGIM.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        txtIMR.setBackground(new java.awt.Color(255, 255, 255));
        txtIMR.setForeground(java.awt.Color.lightGray);
        txtIMR.setText("Ingrese el ID de la nueva materia");
        txtIMR.setBorder(null);
        txtIMR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtIMRMousePressed(evt);
            }
        });
        txtIMR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIMRActionPerformed(evt);
            }
        });
        BGIM.add(txtIMR, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 310, 30));
        BGIM.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 310, 10));

        txtNomR.setBackground(new java.awt.Color(255, 255, 255));
        txtNomR.setForeground(java.awt.Color.lightGray);
        txtNomR.setText("Ingrese el nombre de la nueva materia");
        txtNomR.setBorder(null);
        txtNomR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNomRMousePressed(evt);
            }
        });
        txtNomR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomRActionPerformed(evt);
            }
        });
        BGIM.add(txtNomR, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 310, 30));
        BGIM.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 310, 10));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Nombre de la materia:");
        BGIM.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        btnRA.setBackground(java.awt.Color.orange);
        btnRA.setForeground(java.awt.Color.orange);
        btnRA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("        REGISTRAR");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        btnRA.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 40));

        BGIM.add(btnRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 540, 140, 40));

        btnMA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/angle-left.png"))); // NOI18N
        btnMA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMAMouseClicked(evt);
            }
        });
        BGIM.add(btnMA, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 40, 40));

        TabbedM.addTab("tab2", BGIM);

        BGEM.setBackground(new java.awt.Color(255, 255, 255));
        BGEM.setForeground(new java.awt.Color(255, 255, 255));
        BGEM.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        BGEM.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 310, 10));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("ELIMINAR MATERIA");
        BGEM.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/book (1).png"))); // NOI18N
        BGEM.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 70, 80));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("ID de la materia:");
        BGEM.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        txtMatriE.setBackground(new java.awt.Color(255, 255, 255));
        txtMatriE.setForeground(java.awt.Color.lightGray);
        txtMatriE.setText("Ingrese el ID de la materia a eliminar");
        txtMatriE.setBorder(null);
        txtMatriE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtMatriEMousePressed(evt);
            }
        });
        txtMatriE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatriEActionPerformed(evt);
            }
        });
        BGEM.add(txtMatriE, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 310, 30));
        BGEM.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 310, 10));

        btnEA.setBackground(java.awt.Color.orange);
        btnEA.setForeground(java.awt.Color.orange);
        btnEA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("          ELIMINAR");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel15MouseExited(evt);
            }
        });
        btnEA.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 40));

        BGEM.add(btnEA, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 540, 140, 40));

        btnMA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/angle-left.png"))); // NOI18N
        btnMA1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMA1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMA1MouseClicked(evt);
            }
        });
        BGEM.add(btnMA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 40, 40));

        TabbedM.addTab("tab2", BGEM);

        BGAM.setBackground(new java.awt.Color(255, 255, 255));
        BGAM.setForeground(new java.awt.Color(255, 255, 255));
        BGAM.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        BGAM.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 310, 10));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("ACTUALIZAR MATERIA");
        BGAM.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/book (1).png"))); // NOI18N
        BGAM.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 70, 80));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Ingresa los nuevos datos del alumno");
        BGAM.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        txtIA.setBackground(new java.awt.Color(255, 255, 255));
        txtIA.setForeground(java.awt.Color.lightGray);
        txtIA.setText("Ingrese el nuevo ID de la materia");
        txtIA.setBorder(null);
        txtIA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtIAMousePressed(evt);
            }
        });
        txtIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIAActionPerformed(evt);
            }
        });
        BGAM.add(txtIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 310, 30));
        BGAM.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 310, 10));

        txtNomA.setBackground(new java.awt.Color(255, 255, 255));
        txtNomA.setForeground(java.awt.Color.lightGray);
        txtNomA.setText("Ingrese el nuevo nombre de la materia");
        txtNomA.setBorder(null);
        txtNomA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNomAMousePressed(evt);
            }
        });
        txtNomA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomAActionPerformed(evt);
            }
        });
        BGAM.add(txtNomA, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 310, 30));
        BGAM.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 310, 10));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Nombre de la materia:");
        BGAM.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        btnAAL.setBackground(java.awt.Color.orange);
        btnAAL.setForeground(java.awt.Color.orange);
        btnAAL.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAAL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("       ACTUALIZAR");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel19MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel19MouseExited(evt);
            }
        });
        btnAAL.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 40));

        BGAM.add(btnAAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 540, 140, 40));

        btnMA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/angle-left.png"))); // NOI18N
        btnMA2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMA2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMA2MouseClicked(evt);
            }
        });
        BGAM.add(btnMA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 40, 40));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setText("ID de la materia:");
        BGAM.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        TabbedM.addTab("tab2", BGAM);

        BGAM1.setBackground(new java.awt.Color(255, 255, 255));
        BGAM1.setForeground(new java.awt.Color(255, 255, 255));
        BGAM1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        BGAM1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 310, 10));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText("BUSCAR MATERIA");
        BGAM1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/book (1).png"))); // NOI18N
        BGAM1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 70, 80));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setText("ID de la materia:");
        BGAM1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        txtIA1.setBackground(new java.awt.Color(255, 255, 255));
        txtIA1.setForeground(java.awt.Color.lightGray);
        txtIA1.setText("Ingrese el ID de la materia");
        txtIA1.setBorder(null);
        txtIA1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtIA1MousePressed(evt);
            }
        });
        txtIA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIA1ActionPerformed(evt);
            }
        });
        BGAM1.add(txtIA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 310, 30));
        BGAM1.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 310, 10));

        btnBA.setBackground(java.awt.Color.orange);
        btnBA.setForeground(java.awt.Color.orange);
        btnBA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setText("          BUSCAR");
        jLabel25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel25MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel25MouseExited(evt);
            }
        });
        btnBA.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 40));

        BGAM1.add(btnBA, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 540, 140, 40));

        btnMA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/angle-left.png"))); // NOI18N
        btnMA3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMA3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMA3MouseClicked(evt);
            }
        });
        BGAM1.add(btnMA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 40, 40));

        TabbedM.addTab("tab2", BGAM1);

        getContentPane().add(TabbedM, new org.netbeans.lib.awtextra.AbsoluteConstraints(-14, -39, 500, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PnlMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlMenuMouseClicked
        this.dispose();
        menu.setVisible(true);
        menu.setResizable(false);
        menu.setLocationRelativeTo(null);
    }//GEN-LAST:event_PnlMenuMouseClicked

    private void PnlMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlMenuMouseEntered
        PnlMenu.setBackground(Color.blue);
    }//GEN-LAST:event_PnlMenuMouseEntered

    private void PnlMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlMenuMouseExited
        PnlMenu.setBackground(Color.white);
    }//GEN-LAST:event_PnlMenuMouseExited

    private void PnlCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_PnlCerrarMouseClicked

    private void PnlCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlCerrarMouseEntered
        PnlCerrar.setBackground(Color.red);
        BtnCerrar.setForeground(Color.white);
    }//GEN-LAST:event_PnlCerrarMouseEntered

    private void PnlCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlCerrarMouseExited
        PnlCerrar.setBackground(Color.white);
        BtnCerrar.setForeground(Color.black);
    }//GEN-LAST:event_PnlCerrarMouseExited

    private void BrraTopMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BrraTopMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_BrraTopMouseDragged

    private void BrraTopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BrraTopMousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_BrraTopMousePressed

    private void btnAUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAUMouseClicked
        TabbedM.setSelectedIndex(4);
    }//GEN-LAST:event_btnAUMouseClicked

    private void btnAUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAUMouseEntered
        panelAU.setBackground(new Color(255, 152,20));
    }//GEN-LAST:event_btnAUMouseEntered

    private void btnAUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAUMouseExited
        panelAU.setBackground(new Color(255, 200, 0));
    }//GEN-LAST:event_btnAUMouseExited

    private void panelAUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAUMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelAUMouseEntered

    private void btnAAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAAMouseClicked
        TabbedM.setSelectedIndex(1);
    }//GEN-LAST:event_btnAAMouseClicked

    private void btnAAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAAMouseEntered
        panelAA.setBackground(new Color(255, 152,20));
    }//GEN-LAST:event_btnAAMouseEntered

    private void btnAAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAAMouseExited
        panelAA.setBackground(new Color(255, 200, 0));
    }//GEN-LAST:event_btnAAMouseExited

    private void panelAAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAAMouseEntered
        panelAA.setBackground(new Color(255, 152,20));
    }//GEN-LAST:event_panelAAMouseEntered

    private void btnADMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnADMouseClicked
        TabbedM.setSelectedIndex(2);
    }//GEN-LAST:event_btnADMouseClicked

    private void btnADMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnADMouseEntered
        panelAE.setBackground(new Color(255, 152, 20));
    }//GEN-LAST:event_btnADMouseEntered

    private void btnADMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnADMouseExited
        panelAE.setBackground(new Color(255, 200, 0));
    }//GEN-LAST:event_btnADMouseExited

    private void panelAEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAEMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelAEMouseEntered

    private void txtIMRMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIMRMousePressed
        if (txtIMR.getText().equals("Ingrese el ID de la nueva materia")){
            txtIMR.setText("");
            txtIMR.setForeground(Color.black);
        }
        if (txtNomR.getText().isEmpty()){
            txtNomR.setText("Ingrese el nombre de la nueva materia");
            txtNomR.setForeground(Color.lightGray);
        }
    }//GEN-LAST:event_txtIMRMousePressed

    private void txtIMRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIMRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIMRActionPerformed

    private void txtNomRMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNomRMousePressed
        if (txtNomR.getText().equals("Ingrese el nombre de la nueva materia")){
            txtNomR.setText("");
            txtNomR.setForeground(Color.black);
        }
        if (txtIMR.getText().isEmpty()){
            txtIMR.setText("Ingrese el ID de la nueva materia");
            txtIMR.setForeground(Color.lightGray);
        }
    }//GEN-LAST:event_txtNomRMousePressed

    private void txtNomRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomRActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        String ID="";
        String nombre="";

        reg=new RegistroBD();
        ID=txtIMR.getText();
        nombre=txtNomR.getText();


        boolean resultado;
        resultado=reg.insertarMateria(ID, nombre);
        if(resultado==true){
            JOptionPane.showMessageDialog(null, "La materia fue registrada con exito.");
            txtIMR.setText("Ingrese el ID de la nueva materia");
            txtNomR.setText("Ingrese el nombre de la nueva materia");


        }else{
            JOptionPane.showMessageDialog(null, "No se pudo guardar la materia, intentalo de nuevo.");
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        btnRA.setBackground(new Color(255, 152, 20));
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        btnRA.setBackground(Color.orange);
    }//GEN-LAST:event_jLabel8MouseExited

    private void btnMAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMAMouseClicked
        TabbedM.setSelectedIndex(0);
    }//GEN-LAST:event_btnMAMouseClicked

    private void txtMatriEMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMatriEMousePressed
        if (txtMatriE.getText().equals("Ingrese el ID de la materia a eliminar")){
            txtMatriE.setText("");
            txtMatriE.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtMatriEMousePressed

    private void txtMatriEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatriEActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked

        el=new EliminarBD();
        String matricula=txtMatriE.getText();
        if(el.eliminarMateria(matricula)==1){
            JOptionPane.showMessageDialog(null, "La materia fue eliminada con exito.");
            txtMatriE.setText("Ingrese el ID de la materia a eliminar");
            txtMatriE.setForeground(Color.lightGray);
        }else{
            JOptionPane.showMessageDialog(null, "No se pudo eliminar la materia.");
        }
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseEntered
        btnEA.setBackground(new Color(255, 152, 20));
    }//GEN-LAST:event_jLabel15MouseEntered

    private void jLabel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseExited
        btnEA.setBackground(Color.orange);
    }//GEN-LAST:event_jLabel15MouseExited

    private void btnMA1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMA1MouseClicked
        TabbedM.setSelectedIndex(0);
    }//GEN-LAST:event_btnMA1MouseClicked

    private void txtIAMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIAMousePressed
        if (txtIA.getText().equals("Ingrese el nuevo ID de la materia")){
            txtIA.setText("");
            txtIA.setForeground(Color.black);
        }
        if (txtNomA.getText().isEmpty()){
            txtNomA.setText("Ingrese el nuevo nombre de la materia");
            txtNomA.setForeground(Color.lightGray);
        }
        
    }//GEN-LAST:event_txtIAMousePressed

    private void txtIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIAActionPerformed

    private void txtNomAMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNomAMousePressed
        if (txtNomA.getText().equals("Ingrese el nuevo nombre de la materia")){
            txtNomA.setText("");
            txtNomA.setForeground(Color.black);
        }
        if (txtIA.getText().isEmpty()){
            txtIA.setText("Ingrese el nuevo ID de la materia");
            txtIA.setForeground(Color.lightGray);
        }
        
    }//GEN-LAST:event_txtNomAMousePressed

    private void txtNomAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomAActionPerformed

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        String matricula=txtIA1.getText();
        String matriculaN="";
        String nombre="";

        reg=new RegistroBD();
        upd=new ActualizarBD();
        matriculaN=txtIA.getText();
        nombre=txtNomA.getText();

        if(upd.actualizarMateria(matricula, matriculaN, nombre)==1){
            JOptionPane.showMessageDialog(null, "La materia se actualizo correctamente");
            txtIA.setText("Ingrese el nuevo ID de la materia");
            txtIA.setForeground(Color.lightGray);
            txtNomA.setText("Ingrese el nuevo nombre de la materia");
            txtNomA.setForeground(Color.lightGray);
        }else{
            JOptionPane.showMessageDialog(null, "Hubo un error para actualizar la materia");

        }
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel19MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseEntered
        btnAAL.setBackground(new Color(255, 152, 20));
    }//GEN-LAST:event_jLabel19MouseEntered

    private void jLabel19MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseExited
        btnAAL.setBackground(Color.orange);
    }//GEN-LAST:event_jLabel19MouseExited

    private void btnMA2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMA2MouseClicked
        TabbedM.setSelectedIndex(0);
    }//GEN-LAST:event_btnMA2MouseClicked

    private void txtIA1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIA1MousePressed
        if (txtIA1.getText().equals("Ingrese el ID de la materia")){
            txtIA1.setText("");
            txtIA1.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtIA1MousePressed

    private void txtIA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIA1ActionPerformed

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        String matricula="";

        in=new InicioBD();
        matricula=txtIA1.getText();

        if(in.consultarMateria(matricula)==1){
            TabbedM.setSelectedIndex(3);
        }else{
            JOptionPane.showMessageDialog(null, "Hubo un error para encontrar la materia");

        }

    }//GEN-LAST:event_jLabel25MouseClicked

    private void jLabel25MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseEntered
        btnBA.setBackground(new Color(255, 152, 20));
    }//GEN-LAST:event_jLabel25MouseEntered

    private void jLabel25MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseExited
        btnBA.setBackground(Color.orange);
    }//GEN-LAST:event_jLabel25MouseExited

    private void btnMA3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMA3MouseClicked
        TabbedM.setSelectedIndex(0);
    }//GEN-LAST:event_btnMA3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewMaterias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BGAM;
    private javax.swing.JPanel BGAM1;
    private javax.swing.JPanel BGEM;
    private javax.swing.JPanel BGIM;
    private javax.swing.JPanel BGMM;
    private javax.swing.JPanel BrraTop;
    private javax.swing.JLabel BtnCerrar;
    private javax.swing.JLabel BtnMenu;
    private javax.swing.JPanel PnlCerrar;
    private javax.swing.JPanel PnlMenu;
    private javax.swing.JTabbedPane TabbedM;
    private javax.swing.JLabel btnAA;
    private javax.swing.JPanel btnAAL;
    private javax.swing.JLabel btnAD;
    private javax.swing.JLabel btnAU;
    private javax.swing.JPanel btnBA;
    private javax.swing.JPanel btnEA;
    private javax.swing.JLabel btnMA;
    private javax.swing.JLabel btnMA1;
    private javax.swing.JLabel btnMA2;
    private javax.swing.JLabel btnMA3;
    private javax.swing.JPanel btnRA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JPanel panelAA;
    private javax.swing.JPanel panelAE;
    private javax.swing.JPanel panelAU;
    private javax.swing.JTextField txtIA;
    private javax.swing.JTextField txtIA1;
    private javax.swing.JTextField txtIMR;
    private javax.swing.JTextField txtMatriE;
    private javax.swing.JTextField txtNomA;
    private javax.swing.JTextField txtNomR;
    // End of variables declaration//GEN-END:variables
}
